,url,repository_url,labels_url,comments_url,events_url,html_url,id,node_id,number,title,user,labels,state,locked,assignee,assignees,milestone,comments,created_at,updated_at,closed_at,author_association,active_lock_reason,draft,pull_request,body,closed_by,reactions,timeline_url,performed_via_github_app,state_reason
0,https://api.github.com/repos/pandas-dev/pandas/issues/60637,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas/issues/60637/labels{/name},https://api.github.com/repos/pandas-dev/pandas/issues/60637/comments,https://api.github.com/repos/pandas-dev/pandas/issues/60637/events,https://github.com/pandas-dev/pandas/pull/60637,2764723015,PR_kwDOAA0YD86Gg1Zt,60637,TST(string dtype): Resolve xfail for interpolate,"{'login': 'rhshadrach', 'id': 45562402, 'node_id': 'MDQ6VXNlcjQ1NTYyNDAy', 'avatar_url': 'https://avatars.githubusercontent.com/u/45562402?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/rhshadrach', 'html_url': 'https://github.com/rhshadrach', 'followers_url': 'https://api.github.com/users/rhshadrach/followers', 'following_url': 'https://api.github.com/users/rhshadrach/following{/other_user}', 'gists_url': 'https://api.github.com/users/rhshadrach/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/rhshadrach/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/rhshadrach/subscriptions', 'organizations_url': 'https://api.github.com/users/rhshadrach/orgs', 'repos_url': 'https://api.github.com/users/rhshadrach/repos', 'events_url': 'https://api.github.com/users/rhshadrach/events{/privacy}', 'received_events_url': 'https://api.github.com/users/rhshadrach/received_events', 'type': 'User', 'user_view_type': 'public', 'site_admin': False}","[{'id': 127685, 'node_id': 'MDU6TGFiZWwxMjc2ODU=', 'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/Testing', 'name': 'Testing', 'color': 'C4A000', 'default': False, 'description': 'pandas testing functions or related to the test suite'}, {'id': 2822342, 'node_id': 'MDU6TGFiZWwyODIyMzQy', 'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/Missing-data', 'name': 'Missing-data', 'color': 'd7e102', 'default': False, 'description': 'np.nan, pd.NaT, pd.NA, dropna, isnull, interpolate'}, {'id': 57522093, 'node_id': 'MDU6TGFiZWw1NzUyMjA5Mw==', 'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/Strings', 'name': 'Strings', 'color': '5319e7', 'default': False, 'description': 'String extension data type and string data'}]",open,False,,[],"{'url': 'https://api.github.com/repos/pandas-dev/pandas/milestones/119', 'html_url': 'https://github.com/pandas-dev/pandas/milestone/119', 'labels_url': 'https://api.github.com/repos/pandas-dev/pandas/milestones/119/labels', 'id': 11466880, 'node_id': 'MI_kwDOAA0YD84ArviA', 'number': 119, 'title': '2.3', 'description': 'on-merge: backport to 2.3.x', 'creator': {'login': 'jorisvandenbossche', 'id': 1020496, 'node_id': 'MDQ6VXNlcjEwMjA0OTY=', 'avatar_url': 'https://avatars.githubusercontent.com/u/1020496?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/jorisvandenbossche', 'html_url': 'https://github.com/jorisvandenbossche', 'followers_url': 'https://api.github.com/users/jorisvandenbossche/followers', 'following_url': 'https://api.github.com/users/jorisvandenbossche/following{/other_user}', 'gists_url': 'https://api.github.com/users/jorisvandenbossche/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/jorisvandenbossche/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/jorisvandenbossche/subscriptions', 'organizations_url': 'https://api.github.com/users/jorisvandenbossche/orgs', 'repos_url': 'https://api.github.com/users/jorisvandenbossche/repos', 'events_url': 'https://api.github.com/users/jorisvandenbossche/events{/privacy}', 'received_events_url': 'https://api.github.com/users/jorisvandenbossche/received_events', 'type': 'User', 'user_view_type': 'public', 'site_admin': False}, 'open_issues': 53, 'closed_issues': 215, 'state': 'open', 'created_at': '2024-08-20T19:39:44Z', 'updated_at': '2024-12-31T23:24:47Z', 'due_on': None, 'closed_at': None}",0,2024-12-31T23:24:47Z,2024-12-31T23:25:28Z,,MEMBER,,False,"{'url': 'https://api.github.com/repos/pandas-dev/pandas/pulls/60637', 'html_url': 'https://github.com/pandas-dev/pandas/pull/60637', 'diff_url': 'https://github.com/pandas-dev/pandas/pull/60637.diff', 'patch_url': 'https://github.com/pandas-dev/pandas/pull/60637.patch', 'merged_at': None}","- [ ] closes #xxxx (Replace xxxx with the GitHub issue number)
- [ ] [Tests added and passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#writing-tests) if fixing a bug or adding a new feature
- [ ] All [code checks passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#pre-commit).
- [ ] Added [type annotations](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#type-hints) to new arguments/methods/functions.
- [ ] Added an entry in the latest `doc/source/whatsnew/vX.X.X.rst` file if fixing a bug or adding a new feature.
",,"{'url': 'https://api.github.com/repos/pandas-dev/pandas/issues/60637/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}",https://api.github.com/repos/pandas-dev/pandas/issues/60637/timeline,,
1,https://api.github.com/repos/pandas-dev/pandas/issues/60636,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas/issues/60636/labels{/name},https://api.github.com/repos/pandas-dev/pandas/issues/60636/comments,https://api.github.com/repos/pandas-dev/pandas/issues/60636/events,https://github.com/pandas-dev/pandas/pull/60636,2764717941,PR_kwDOAA0YD86Gg0bn,60636,TST(string dtype): Resolve xfail with apply returning an ndarray,"{'login': 'rhshadrach', 'id': 45562402, 'node_id': 'MDQ6VXNlcjQ1NTYyNDAy', 'avatar_url': 'https://avatars.githubusercontent.com/u/45562402?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/rhshadrach', 'html_url': 'https://github.com/rhshadrach', 'followers_url': 'https://api.github.com/users/rhshadrach/followers', 'following_url': 'https://api.github.com/users/rhshadrach/following{/other_user}', 'gists_url': 'https://api.github.com/users/rhshadrach/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/rhshadrach/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/rhshadrach/subscriptions', 'organizations_url': 'https://api.github.com/users/rhshadrach/orgs', 'repos_url': 'https://api.github.com/users/rhshadrach/repos', 'events_url': 'https://api.github.com/users/rhshadrach/events{/privacy}', 'received_events_url': 'https://api.github.com/users/rhshadrach/received_events', 'type': 'User', 'user_view_type': 'public', 'site_admin': False}","[{'id': 127685, 'node_id': 'MDU6TGFiZWwxMjc2ODU=', 'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/Testing', 'name': 'Testing', 'color': 'C4A000', 'default': False, 'description': 'pandas testing functions or related to the test suite'}, {'id': 57522093, 'node_id': 'MDU6TGFiZWw1NzUyMjA5Mw==', 'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/Strings', 'name': 'Strings', 'color': '5319e7', 'default': False, 'description': 'String extension data type and string data'}, {'id': 697792067, 'node_id': 'MDU6TGFiZWw2OTc3OTIwNjc=', 'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/Apply', 'name': 'Apply', 'color': 'fbca04', 'default': False, 'description': 'Apply, Aggregate, Transform, Map'}]",open,False,,[],,0,2024-12-31T23:08:05Z,2024-12-31T23:08:32Z,,MEMBER,,False,"{'url': 'https://api.github.com/repos/pandas-dev/pandas/pulls/60636', 'html_url': 'https://github.com/pandas-dev/pandas/pull/60636', 'diff_url': 'https://github.com/pandas-dev/pandas/pull/60636.diff', 'patch_url': 'https://github.com/pandas-dev/pandas/pull/60636.patch', 'merged_at': None}","- [ ] closes #xxxx (Replace xxxx with the GitHub issue number)
- [ ] [Tests added and passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#writing-tests) if fixing a bug or adding a new feature
- [ ] All [code checks passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#pre-commit).
- [ ] Added [type annotations](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#type-hints) to new arguments/methods/functions.
- [ ] Added an entry in the latest `doc/source/whatsnew/vX.X.X.rst` file if fixing a bug or adding a new feature.

Ref: #35517

The `expected` is different than the `result` (even in the case where `using_infer_string=False`) but gets through `assert_series_equal` okay because:

```python
print(np.array(""bar"") == ""bar"")
# np.True_
```

This PR fixes `expected` so that it is the same as `result`. I don't see any way to improve `assert_series_equal` here - it's an object dtype Series and I think we can only expect `assert_series_equal` to test up to equality of the underlying Python objects.",,"{'url': 'https://api.github.com/repos/pandas-dev/pandas/issues/60636/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}",https://api.github.com/repos/pandas-dev/pandas/issues/60636/timeline,,
2,https://api.github.com/repos/pandas-dev/pandas/issues/60635,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas/issues/60635/labels{/name},https://api.github.com/repos/pandas-dev/pandas/issues/60635/comments,https://api.github.com/repos/pandas-dev/pandas/issues/60635/events,https://github.com/pandas-dev/pandas/pull/60635,2764713494,PR_kwDOAA0YD86Ggzhk,60635,TST(string dtype): Resolve xfail for corrwith,"{'login': 'rhshadrach', 'id': 45562402, 'node_id': 'MDQ6VXNlcjQ1NTYyNDAy', 'avatar_url': 'https://avatars.githubusercontent.com/u/45562402?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/rhshadrach', 'html_url': 'https://github.com/rhshadrach', 'followers_url': 'https://api.github.com/users/rhshadrach/followers', 'following_url': 'https://api.github.com/users/rhshadrach/following{/other_user}', 'gists_url': 'https://api.github.com/users/rhshadrach/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/rhshadrach/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/rhshadrach/subscriptions', 'organizations_url': 'https://api.github.com/users/rhshadrach/orgs', 'repos_url': 'https://api.github.com/users/rhshadrach/repos', 'events_url': 'https://api.github.com/users/rhshadrach/events{/privacy}', 'received_events_url': 'https://api.github.com/users/rhshadrach/received_events', 'type': 'User', 'user_view_type': 'public', 'site_admin': False}","[{'id': 127685, 'node_id': 'MDU6TGFiZWwxMjc2ODU=', 'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/Testing', 'name': 'Testing', 'color': 'C4A000', 'default': False, 'description': 'pandas testing functions or related to the test suite'}, {'id': 57522093, 'node_id': 'MDU6TGFiZWw1NzUyMjA5Mw==', 'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/Strings', 'name': 'Strings', 'color': '5319e7', 'default': False, 'description': 'String extension data type and string data'}, {'id': 5331296438, 'node_id': 'LA_kwDOAA0YD88AAAABPcUgtg', 'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/cov/corr', 'name': 'cov/corr', 'color': '006b75', 'default': False, 'description': ''}]",open,False,,[],"{'url': 'https://api.github.com/repos/pandas-dev/pandas/milestones/119', 'html_url': 'https://github.com/pandas-dev/pandas/milestone/119', 'labels_url': 'https://api.github.com/repos/pandas-dev/pandas/milestones/119/labels', 'id': 11466880, 'node_id': 'MI_kwDOAA0YD84ArviA', 'number': 119, 'title': '2.3', 'description': 'on-merge: backport to 2.3.x', 'creator': {'login': 'jorisvandenbossche', 'id': 1020496, 'node_id': 'MDQ6VXNlcjEwMjA0OTY=', 'avatar_url': 'https://avatars.githubusercontent.com/u/1020496?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/jorisvandenbossche', 'html_url': 'https://github.com/jorisvandenbossche', 'followers_url': 'https://api.github.com/users/jorisvandenbossche/followers', 'following_url': 'https://api.github.com/users/jorisvandenbossche/following{/other_user}', 'gists_url': 'https://api.github.com/users/jorisvandenbossche/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/jorisvandenbossche/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/jorisvandenbossche/subscriptions', 'organizations_url': 'https://api.github.com/users/jorisvandenbossche/orgs', 'repos_url': 'https://api.github.com/users/jorisvandenbossche/repos', 'events_url': 'https://api.github.com/users/jorisvandenbossche/events{/privacy}', 'received_events_url': 'https://api.github.com/users/jorisvandenbossche/received_events', 'type': 'User', 'user_view_type': 'public', 'site_admin': False}, 'open_issues': 53, 'closed_issues': 215, 'state': 'open', 'created_at': '2024-08-20T19:39:44Z', 'updated_at': '2024-12-31T23:24:47Z', 'due_on': None, 'closed_at': None}",0,2024-12-31T22:53:59Z,2024-12-31T23:05:06Z,,MEMBER,,False,"{'url': 'https://api.github.com/repos/pandas-dev/pandas/pulls/60635', 'html_url': 'https://github.com/pandas-dev/pandas/pull/60635', 'diff_url': 'https://github.com/pandas-dev/pandas/pull/60635.diff', 'patch_url': 'https://github.com/pandas-dev/pandas/pull/60635.patch', 'merged_at': None}","- [ ] closes #xxxx (Replace xxxx with the GitHub issue number)
- [ ] [Tests added and passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#writing-tests) if fixing a bug or adding a new feature
- [ ] All [code checks passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#pre-commit).
- [ ] Added [type annotations](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#type-hints) to new arguments/methods/functions.
- [ ] Added an entry in the latest `doc/source/whatsnew/vX.X.X.rst` file if fixing a bug or adding a new feature.
",,"{'url': 'https://api.github.com/repos/pandas-dev/pandas/issues/60635/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}",https://api.github.com/repos/pandas-dev/pandas/issues/60635/timeline,,
3,https://api.github.com/repos/pandas-dev/pandas/issues/60634,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas/issues/60634/labels{/name},https://api.github.com/repos/pandas-dev/pandas/issues/60634/comments,https://api.github.com/repos/pandas-dev/pandas/issues/60634/events,https://github.com/pandas-dev/pandas/pull/60634,2764708247,PR_kwDOAA0YD86GgydC,60634,TST(string dtype): Remove xfail for combine_first,"{'login': 'rhshadrach', 'id': 45562402, 'node_id': 'MDQ6VXNlcjQ1NTYyNDAy', 'avatar_url': 'https://avatars.githubusercontent.com/u/45562402?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/rhshadrach', 'html_url': 'https://github.com/rhshadrach', 'followers_url': 'https://api.github.com/users/rhshadrach/followers', 'following_url': 'https://api.github.com/users/rhshadrach/following{/other_user}', 'gists_url': 'https://api.github.com/users/rhshadrach/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/rhshadrach/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/rhshadrach/subscriptions', 'organizations_url': 'https://api.github.com/users/rhshadrach/orgs', 'repos_url': 'https://api.github.com/users/rhshadrach/repos', 'events_url': 'https://api.github.com/users/rhshadrach/events{/privacy}', 'received_events_url': 'https://api.github.com/users/rhshadrach/received_events', 'type': 'User', 'user_view_type': 'public', 'site_admin': False}","[{'id': 127685, 'node_id': 'MDU6TGFiZWwxMjc2ODU=', 'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/Testing', 'name': 'Testing', 'color': 'C4A000', 'default': False, 'description': 'pandas testing functions or related to the test suite'}, {'id': 57522093, 'node_id': 'MDU6TGFiZWw1NzUyMjA5Mw==', 'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/Strings', 'name': 'Strings', 'color': '5319e7', 'default': False, 'description': 'String extension data type and string data'}]",open,False,,[],,0,2024-12-31T22:37:10Z,2024-12-31T22:39:11Z,,MEMBER,,False,"{'url': 'https://api.github.com/repos/pandas-dev/pandas/pulls/60634', 'html_url': 'https://github.com/pandas-dev/pandas/pull/60634', 'diff_url': 'https://github.com/pandas-dev/pandas/pull/60634.diff', 'patch_url': 'https://github.com/pandas-dev/pandas/pull/60634.patch', 'merged_at': None}","- [ ] closes #xxxx (Replace xxxx with the GitHub issue number)
- [ ] [Tests added and passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#writing-tests) if fixing a bug or adding a new feature
- [ ] All [code checks passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#pre-commit).
- [ ] Added [type annotations](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#type-hints) to new arguments/methods/functions.
- [ ] Added an entry in the latest `doc/source/whatsnew/vX.X.X.rst` file if fixing a bug or adding a new feature.

This was added in #55409 and no longer raises a warning. I cannot find any warning that matches `empty entries`, I'm guessing the warning itself has been removed.

Edit: found it, the warning was from https://github.com/pandas-dev/pandas/pull/52532.",,"{'url': 'https://api.github.com/repos/pandas-dev/pandas/issues/60634/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}",https://api.github.com/repos/pandas-dev/pandas/issues/60634/timeline,,
4,https://api.github.com/repos/pandas-dev/pandas/issues/60633,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas/issues/60633/labels{/name},https://api.github.com/repos/pandas-dev/pandas/issues/60633/comments,https://api.github.com/repos/pandas-dev/pandas/issues/60633/events,https://github.com/pandas-dev/pandas/pull/60633,2764507851,PR_kwDOAA0YD86GgJAQ,60633,ENH: Implement cum* methods for PyArrow strings,"{'login': 'rhshadrach', 'id': 45562402, 'node_id': 'MDQ6VXNlcjQ1NTYyNDAy', 'avatar_url': 'https://avatars.githubusercontent.com/u/45562402?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/rhshadrach', 'html_url': 'https://github.com/rhshadrach', 'followers_url': 'https://api.github.com/users/rhshadrach/followers', 'following_url': 'https://api.github.com/users/rhshadrach/following{/other_user}', 'gists_url': 'https://api.github.com/users/rhshadrach/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/rhshadrach/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/rhshadrach/subscriptions', 'organizations_url': 'https://api.github.com/users/rhshadrach/orgs', 'repos_url': 'https://api.github.com/users/rhshadrach/repos', 'events_url': 'https://api.github.com/users/rhshadrach/events{/privacy}', 'received_events_url': 'https://api.github.com/users/rhshadrach/received_events', 'type': 'User', 'user_view_type': 'public', 'site_admin': False}","[{'id': 76812, 'node_id': 'MDU6TGFiZWw3NjgxMg==', 'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/Enhancement', 'name': 'Enhancement', 'color': '4E9A06', 'default': False, 'description': None}, {'id': 57522093, 'node_id': 'MDU6TGFiZWw1NzUyMjA5Mw==', 'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/Strings', 'name': 'Strings', 'color': '5319e7', 'default': False, 'description': 'String extension data type and string data'}, {'id': 3303158446, 'node_id': 'MDU6TGFiZWwzMzAzMTU4NDQ2', 'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/Arrow', 'name': 'Arrow', 'color': 'f9d0c4', 'default': False, 'description': 'pyarrow functionality'}, {'id': 5432589519, 'node_id': 'LA_kwDOAA0YD88AAAABQ868zw', 'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/Transformations', 'name': 'Transformations', 'color': '5319e7', 'default': False, 'description': 'e.g. cumsum, diff, rank'}]",open,False,,[],"{'url': 'https://api.github.com/repos/pandas-dev/pandas/milestones/119', 'html_url': 'https://github.com/pandas-dev/pandas/milestone/119', 'labels_url': 'https://api.github.com/repos/pandas-dev/pandas/milestones/119/labels', 'id': 11466880, 'node_id': 'MI_kwDOAA0YD84ArviA', 'number': 119, 'title': '2.3', 'description': 'on-merge: backport to 2.3.x', 'creator': {'login': 'jorisvandenbossche', 'id': 1020496, 'node_id': 'MDQ6VXNlcjEwMjA0OTY=', 'avatar_url': 'https://avatars.githubusercontent.com/u/1020496?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/jorisvandenbossche', 'html_url': 'https://github.com/jorisvandenbossche', 'followers_url': 'https://api.github.com/users/jorisvandenbossche/followers', 'following_url': 'https://api.github.com/users/jorisvandenbossche/following{/other_user}', 'gists_url': 'https://api.github.com/users/jorisvandenbossche/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/jorisvandenbossche/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/jorisvandenbossche/subscriptions', 'organizations_url': 'https://api.github.com/users/jorisvandenbossche/orgs', 'repos_url': 'https://api.github.com/users/jorisvandenbossche/repos', 'events_url': 'https://api.github.com/users/jorisvandenbossche/events{/privacy}', 'received_events_url': 'https://api.github.com/users/jorisvandenbossche/received_events', 'type': 'User', 'user_view_type': 'public', 'site_admin': False}, 'open_issues': 53, 'closed_issues': 215, 'state': 'open', 'created_at': '2024-08-20T19:39:44Z', 'updated_at': '2024-12-31T23:24:47Z', 'due_on': None, 'closed_at': None}",1,2024-12-31T16:07:14Z,2024-12-31T17:16:26Z,,MEMBER,,False,"{'url': 'https://api.github.com/repos/pandas-dev/pandas/pulls/60633', 'html_url': 'https://github.com/pandas-dev/pandas/pull/60633', 'diff_url': 'https://github.com/pandas-dev/pandas/pull/60633.diff', 'patch_url': 'https://github.com/pandas-dev/pandas/pull/60633.patch', 'merged_at': None}","- [ ] closes #xxxx (Replace xxxx with the GitHub issue number)
- [ ] [Tests added and passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#writing-tests) if fixing a bug or adding a new feature
- [ ] All [code checks passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#pre-commit).
- [ ] Added [type annotations](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#type-hints) to new arguments/methods/functions.
- [ ] Added an entry in the latest `doc/source/whatsnew/vX.X.X.rst` file if fixing a bug or adding a new feature.

Implements `cumsum`, `cummin`, and `cummax` for PyArrow-backed strings. I don't see a way to do this without passing through NumPy - if there are other ideas for approaching happy to give those a shot.

cc @WillAyd @jorisvandenbossche ",,"{'url': 'https://api.github.com/repos/pandas-dev/pandas/issues/60633/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}",https://api.github.com/repos/pandas-dev/pandas/issues/60633/timeline,,
5,https://api.github.com/repos/pandas-dev/pandas/issues/60632,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas/issues/60632/labels{/name},https://api.github.com/repos/pandas-dev/pandas/issues/60632/comments,https://api.github.com/repos/pandas-dev/pandas/issues/60632/events,https://github.com/pandas-dev/pandas/issues/60632,2764373991,I_kwDOAA0YD86kxP_n,60632,DOC: Comparing .loc/.iloc to tuples and chained indexing,"{'login': 'johnasiano', 'id': 54973763, 'node_id': 'MDQ6VXNlcjU0OTczNzYz', 'avatar_url': 'https://avatars.githubusercontent.com/u/54973763?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/johnasiano', 'html_url': 'https://github.com/johnasiano', 'followers_url': 'https://api.github.com/users/johnasiano/followers', 'following_url': 'https://api.github.com/users/johnasiano/following{/other_user}', 'gists_url': 'https://api.github.com/users/johnasiano/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/johnasiano/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/johnasiano/subscriptions', 'organizations_url': 'https://api.github.com/users/johnasiano/orgs', 'repos_url': 'https://api.github.com/users/johnasiano/repos', 'events_url': 'https://api.github.com/users/johnasiano/events{/privacy}', 'received_events_url': 'https://api.github.com/users/johnasiano/received_events', 'type': 'User', 'user_view_type': 'public', 'site_admin': False}","[{'id': 134699, 'node_id': 'MDU6TGFiZWwxMzQ2OTk=', 'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/Docs', 'name': 'Docs', 'color': '3465A4', 'default': False, 'description': None}, {'id': 2822098, 'node_id': 'MDU6TGFiZWwyODIyMDk4', 'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/Indexing', 'name': 'Indexing', 'color': '0b02e1', 'default': False, 'description': 'Related to indexing on series/frames, not to indexes themselves'}, {'id': 219960758, 'node_id': 'MDU6TGFiZWwyMTk5NjA3NTg=', 'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/Needs%20Discussion', 'name': 'Needs Discussion', 'color': '207de5', 'default': False, 'description': 'Requires discussion from core team before further action'}]",open,False,,[],,1,2024-12-31T13:21:15Z,2024-12-31T16:48:17Z,,NONE,,,,"### Pandas version checks

- [X] I have checked that the issue still exists on the latest versions of the docs on `main` [here](https://pandas.pydata.org/docs/dev/)


### Location of the documentation

https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#indexing-view-versus-copy





### Documentation problem

```
import pandas as pd

# Creating a DataFrame with some sample data
data = {
    'Name': [Jason, 'Emma', 'Alex', 'Sarah'],
    'Age': [28, 24, 32, 27],
    'City': ['New York', 'London', 'Paris', 'Tokyo'],
    'Salary': [75000, 65000, 85000, 70000]
}

df = pd.DataFrame(data)

# Display the DataFrame
print(df)

I want to update Jason’s age, and I do so with 

df['Age'][df['Name'] == 'Jason'] = 29


```

For code such as the code shown above, the df may or may not be update Jason's age to 29 due to the chained indexing that is being used. 

The documentation mentions how .iloc/.loc is a better option. For example, something such as the following.

`df.loc[df['Name'] == 'Jason', 'Age'] = 29`

However it is not clear about best practices regarding tuples, such as the following.

`df[('Age', df['Name'] == 'Jason')] = 29
`


### Suggested fix for documentation

The suggested fix is to explain how the use of tuples would compare to the use of .iloc/.loc and the use of chained indexing in the context of best practices in pandas. Considerations can include time complexity, space complexity, code readability, etc. ",,"{'url': 'https://api.github.com/repos/pandas-dev/pandas/issues/60632/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}",https://api.github.com/repos/pandas-dev/pandas/issues/60632/timeline,,
6,https://api.github.com/repos/pandas-dev/pandas/issues/60629,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas/issues/60629/labels{/name},https://api.github.com/repos/pandas-dev/pandas/issues/60629/comments,https://api.github.com/repos/pandas-dev/pandas/issues/60629/events,https://github.com/pandas-dev/pandas/pull/60629,2763689632,PR_kwDOAA0YD86GdZqN,60629,Implement first-class List type,"{'login': 'WillAyd', 'id': 609873, 'node_id': 'MDQ6VXNlcjYwOTg3Mw==', 'avatar_url': 'https://avatars.githubusercontent.com/u/609873?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/WillAyd', 'html_url': 'https://github.com/WillAyd', 'followers_url': 'https://api.github.com/users/WillAyd/followers', 'following_url': 'https://api.github.com/users/WillAyd/following{/other_user}', 'gists_url': 'https://api.github.com/users/WillAyd/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/WillAyd/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/WillAyd/subscriptions', 'organizations_url': 'https://api.github.com/users/WillAyd/orgs', 'repos_url': 'https://api.github.com/users/WillAyd/repos', 'events_url': 'https://api.github.com/users/WillAyd/events{/privacy}', 'received_events_url': 'https://api.github.com/users/WillAyd/received_events', 'type': 'User', 'user_view_type': 'public', 'site_admin': False}",[],open,False,,[],,5,2024-12-30T20:58:17Z,2024-12-31T19:06:10Z,,MEMBER,,True,"{'url': 'https://api.github.com/repos/pandas-dev/pandas/pulls/60629', 'html_url': 'https://github.com/pandas-dev/pandas/pull/60629', 'diff_url': 'https://github.com/pandas-dev/pandas/pull/60629.diff', 'patch_url': 'https://github.com/pandas-dev/pandas/pull/60629.patch', 'merged_at': None}","Quick POC for now. There's a lot to do here but hoping to work in pieces. This currently assumes pyarrow is installed.

The blocks / formatting stuff is not super familiar to me so hoping @mroeschke or @jbrockmendel might have some ideas on how to better approach. I think the main problem I am having is the Block seems to want to infer the type from the values contained. That works for NumPy, but doesn't work with PyArrow, for example when you have an array of all `nulls` that is separately paired with a type of`list[string]` ",,"{'url': 'https://api.github.com/repos/pandas-dev/pandas/issues/60629/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}",https://api.github.com/repos/pandas-dev/pandas/issues/60629/timeline,,
7,https://api.github.com/repos/pandas-dev/pandas/issues/60627,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas/issues/60627/labels{/name},https://api.github.com/repos/pandas-dev/pandas/issues/60627/comments,https://api.github.com/repos/pandas-dev/pandas/issues/60627/events,https://github.com/pandas-dev/pandas/pull/60627,2763336776,PR_kwDOAA0YD86GcOMr,60627,TST(string dtype): Resolve HDF5 xfails in test_round_trip.py,"{'login': 'rhshadrach', 'id': 45562402, 'node_id': 'MDQ6VXNlcjQ1NTYyNDAy', 'avatar_url': 'https://avatars.githubusercontent.com/u/45562402?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/rhshadrach', 'html_url': 'https://github.com/rhshadrach', 'followers_url': 'https://api.github.com/users/rhshadrach/followers', 'following_url': 'https://api.github.com/users/rhshadrach/following{/other_user}', 'gists_url': 'https://api.github.com/users/rhshadrach/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/rhshadrach/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/rhshadrach/subscriptions', 'organizations_url': 'https://api.github.com/users/rhshadrach/orgs', 'repos_url': 'https://api.github.com/users/rhshadrach/repos', 'events_url': 'https://api.github.com/users/rhshadrach/events{/privacy}', 'received_events_url': 'https://api.github.com/users/rhshadrach/received_events', 'type': 'User', 'user_view_type': 'public', 'site_admin': False}","[{'id': 47229190, 'node_id': 'MDU6TGFiZWw0NzIyOTE5MA==', 'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/IO%20HDF5', 'name': 'IO HDF5', 'color': '5319e7', 'default': False, 'description': 'read_hdf, HDFStore'}, {'id': 57522093, 'node_id': 'MDU6TGFiZWw1NzUyMjA5Mw==', 'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/Strings', 'name': 'Strings', 'color': '5319e7', 'default': False, 'description': 'String extension data type and string data'}]",open,False,,[],"{'url': 'https://api.github.com/repos/pandas-dev/pandas/milestones/119', 'html_url': 'https://github.com/pandas-dev/pandas/milestone/119', 'labels_url': 'https://api.github.com/repos/pandas-dev/pandas/milestones/119/labels', 'id': 11466880, 'node_id': 'MI_kwDOAA0YD84ArviA', 'number': 119, 'title': '2.3', 'description': 'on-merge: backport to 2.3.x', 'creator': {'login': 'jorisvandenbossche', 'id': 1020496, 'node_id': 'MDQ6VXNlcjEwMjA0OTY=', 'avatar_url': 'https://avatars.githubusercontent.com/u/1020496?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/jorisvandenbossche', 'html_url': 'https://github.com/jorisvandenbossche', 'followers_url': 'https://api.github.com/users/jorisvandenbossche/followers', 'following_url': 'https://api.github.com/users/jorisvandenbossche/following{/other_user}', 'gists_url': 'https://api.github.com/users/jorisvandenbossche/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/jorisvandenbossche/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/jorisvandenbossche/subscriptions', 'organizations_url': 'https://api.github.com/users/jorisvandenbossche/orgs', 'repos_url': 'https://api.github.com/users/jorisvandenbossche/repos', 'events_url': 'https://api.github.com/users/jorisvandenbossche/events{/privacy}', 'received_events_url': 'https://api.github.com/users/jorisvandenbossche/received_events', 'type': 'User', 'user_view_type': 'public', 'site_admin': False}, 'open_issues': 53, 'closed_issues': 215, 'state': 'open', 'created_at': '2024-08-20T19:39:44Z', 'updated_at': '2024-12-31T23:24:47Z', 'due_on': None, 'closed_at': None}",0,2024-12-30T15:05:34Z,2024-12-30T20:20:47Z,,MEMBER,,False,"{'url': 'https://api.github.com/repos/pandas-dev/pandas/pulls/60627', 'html_url': 'https://github.com/pandas-dev/pandas/pull/60627', 'diff_url': 'https://github.com/pandas-dev/pandas/pull/60627.diff', 'patch_url': 'https://github.com/pandas-dev/pandas/pull/60627.patch', 'merged_at': None}","- [ ] closes #xxxx (Replace xxxx with the GitHub issue number)
- [ ] [Tests added and passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#writing-tests) if fixing a bug or adding a new feature
- [ ] All [code checks passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#pre-commit).
- [ ] Added [type annotations](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#type-hints) to new arguments/methods/functions.
- [ ] Added an entry in the latest `doc/source/whatsnew/vX.X.X.rst` file if fixing a bug or adding a new feature.

Built on top of #60625",,"{'url': 'https://api.github.com/repos/pandas-dev/pandas/issues/60627/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}",https://api.github.com/repos/pandas-dev/pandas/issues/60627/timeline,,
8,https://api.github.com/repos/pandas-dev/pandas/issues/60625,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas/issues/60625/labels{/name},https://api.github.com/repos/pandas-dev/pandas/issues/60625/comments,https://api.github.com/repos/pandas-dev/pandas/issues/60625/events,https://github.com/pandas-dev/pandas/pull/60625,2763247428,PR_kwDOAA0YD86Gb66q,60625,TST(string dtype): Resolve HDF5 xfails in test_put.py,"{'login': 'rhshadrach', 'id': 45562402, 'node_id': 'MDQ6VXNlcjQ1NTYyNDAy', 'avatar_url': 'https://avatars.githubusercontent.com/u/45562402?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/rhshadrach', 'html_url': 'https://github.com/rhshadrach', 'followers_url': 'https://api.github.com/users/rhshadrach/followers', 'following_url': 'https://api.github.com/users/rhshadrach/following{/other_user}', 'gists_url': 'https://api.github.com/users/rhshadrach/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/rhshadrach/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/rhshadrach/subscriptions', 'organizations_url': 'https://api.github.com/users/rhshadrach/orgs', 'repos_url': 'https://api.github.com/users/rhshadrach/repos', 'events_url': 'https://api.github.com/users/rhshadrach/events{/privacy}', 'received_events_url': 'https://api.github.com/users/rhshadrach/received_events', 'type': 'User', 'user_view_type': 'public', 'site_admin': False}","[{'id': 47229190, 'node_id': 'MDU6TGFiZWw0NzIyOTE5MA==', 'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/IO%20HDF5', 'name': 'IO HDF5', 'color': '5319e7', 'default': False, 'description': 'read_hdf, HDFStore'}, {'id': 57522093, 'node_id': 'MDU6TGFiZWw1NzUyMjA5Mw==', 'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/Strings', 'name': 'Strings', 'color': '5319e7', 'default': False, 'description': 'String extension data type and string data'}]",open,False,,[],"{'url': 'https://api.github.com/repos/pandas-dev/pandas/milestones/119', 'html_url': 'https://github.com/pandas-dev/pandas/milestone/119', 'labels_url': 'https://api.github.com/repos/pandas-dev/pandas/milestones/119/labels', 'id': 11466880, 'node_id': 'MI_kwDOAA0YD84ArviA', 'number': 119, 'title': '2.3', 'description': 'on-merge: backport to 2.3.x', 'creator': {'login': 'jorisvandenbossche', 'id': 1020496, 'node_id': 'MDQ6VXNlcjEwMjA0OTY=', 'avatar_url': 'https://avatars.githubusercontent.com/u/1020496?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/jorisvandenbossche', 'html_url': 'https://github.com/jorisvandenbossche', 'followers_url': 'https://api.github.com/users/jorisvandenbossche/followers', 'following_url': 'https://api.github.com/users/jorisvandenbossche/following{/other_user}', 'gists_url': 'https://api.github.com/users/jorisvandenbossche/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/jorisvandenbossche/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/jorisvandenbossche/subscriptions', 'organizations_url': 'https://api.github.com/users/jorisvandenbossche/orgs', 'repos_url': 'https://api.github.com/users/jorisvandenbossche/repos', 'events_url': 'https://api.github.com/users/jorisvandenbossche/events{/privacy}', 'received_events_url': 'https://api.github.com/users/jorisvandenbossche/received_events', 'type': 'User', 'user_view_type': 'public', 'site_admin': False}, 'open_issues': 53, 'closed_issues': 215, 'state': 'open', 'created_at': '2024-08-20T19:39:44Z', 'updated_at': '2024-12-31T23:24:47Z', 'due_on': None, 'closed_at': None}",0,2024-12-30T13:56:20Z,2024-12-31T17:27:56Z,,MEMBER,,False,"{'url': 'https://api.github.com/repos/pandas-dev/pandas/pulls/60625', 'html_url': 'https://github.com/pandas-dev/pandas/pull/60625', 'diff_url': 'https://github.com/pandas-dev/pandas/pull/60625.diff', 'patch_url': 'https://github.com/pandas-dev/pandas/pull/60625.patch', 'merged_at': None}","- [ ] closes #xxxx (Replace xxxx with the GitHub issue number)
- [ ] [Tests added and passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#writing-tests) if fixing a bug or adding a new feature
- [ ] All [code checks passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#pre-commit).
- [ ] Added [type annotations](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#type-hints) to new arguments/methods/functions.
- [ ] Added an entry in the latest `doc/source/whatsnew/vX.X.X.rst` file if fixing a bug or adding a new feature.

It would be more performant to implement a way of writing the string dtypes without converting to NumPy, but this approach gets us correct behavior for now.",,"{'url': 'https://api.github.com/repos/pandas-dev/pandas/issues/60625/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}",https://api.github.com/repos/pandas-dev/pandas/issues/60625/timeline,,
9,https://api.github.com/repos/pandas-dev/pandas/issues/60624,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas/issues/60624/labels{/name},https://api.github.com/repos/pandas-dev/pandas/issues/60624/comments,https://api.github.com/repos/pandas-dev/pandas/issues/60624/events,https://github.com/pandas-dev/pandas/pull/60624,2763126262,PR_kwDOAA0YD86Gbglc,60624,Update timestamps.pyx,"{'login': 'johnasiano', 'id': 54973763, 'node_id': 'MDQ6VXNlcjU0OTczNzYz', 'avatar_url': 'https://avatars.githubusercontent.com/u/54973763?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/johnasiano', 'html_url': 'https://github.com/johnasiano', 'followers_url': 'https://api.github.com/users/johnasiano/followers', 'following_url': 'https://api.github.com/users/johnasiano/following{/other_user}', 'gists_url': 'https://api.github.com/users/johnasiano/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/johnasiano/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/johnasiano/subscriptions', 'organizations_url': 'https://api.github.com/users/johnasiano/orgs', 'repos_url': 'https://api.github.com/users/johnasiano/repos', 'events_url': 'https://api.github.com/users/johnasiano/events{/privacy}', 'received_events_url': 'https://api.github.com/users/johnasiano/received_events', 'type': 'User', 'user_view_type': 'public', 'site_admin': False}","[{'id': 76811, 'node_id': 'MDU6TGFiZWw3NjgxMQ==', 'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/Bug', 'name': 'Bug', 'color': 'e10c02', 'default': False, 'description': None}, {'id': 3877216987, 'node_id': 'LA_kwDOAA0YD87nGaLb', 'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/Timestamp', 'name': 'Timestamp', 'color': '5DE3E8', 'default': False, 'description': 'pd.Timestamp and associated methods'}]",open,False,,[],,0,2024-12-30T12:17:02Z,2024-12-31T15:38:08Z,,NONE,,False,"{'url': 'https://api.github.com/repos/pandas-dev/pandas/pulls/60624', 'html_url': 'https://github.com/pandas-dev/pandas/pull/60624', 'diff_url': 'https://github.com/pandas-dev/pandas/pull/60624.diff', 'patch_url': 'https://github.com/pandas-dev/pandas/pull/60624.patch', 'merged_at': None}","- [ ] closes #xxxx (Replace xxxx with the GitHub issue number)
- [ ] [Tests added and passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#writing-tests) if fixing a bug or adding a new feature
- [ ] All [code checks passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#pre-commit).
- [ ] Added [type annotations](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#type-hints) to new arguments/methods/functions.
- [ ] Added an entry in the latest `doc/source/whatsnew/vX.X.X.rst` file if fixing a bug or adding a new feature.

Proposing a change to fix this issue: https://github.com/pandas-dev/pandas/issues/60583. My understanding is that the bug is due to the code logic described in timestamps.pyx. 

The first option that I considered was modifying normalize in timestamps.pyx. The second option that I considered was modifying normalize_i8_stamp() in timestamps.pyx, and also updating normalize_i8_stamp() in timestamps.pxd to update the normalize_i8_stamp() declaration to match the new signature.

datetimes.py would not be modified because my understanding is that this overflow issue is not present in datetimes. 
","{'login': 'johnasiano', 'id': 54973763, 'node_id': 'MDQ6VXNlcjU0OTczNzYz', 'avatar_url': 'https://avatars.githubusercontent.com/u/54973763?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/johnasiano', 'html_url': 'https://github.com/johnasiano', 'followers_url': 'https://api.github.com/users/johnasiano/followers', 'following_url': 'https://api.github.com/users/johnasiano/following{/other_user}', 'gists_url': 'https://api.github.com/users/johnasiano/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/johnasiano/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/johnasiano/subscriptions', 'organizations_url': 'https://api.github.com/users/johnasiano/orgs', 'repos_url': 'https://api.github.com/users/johnasiano/repos', 'events_url': 'https://api.github.com/users/johnasiano/events{/privacy}', 'received_events_url': 'https://api.github.com/users/johnasiano/received_events', 'type': 'User', 'user_view_type': 'public', 'site_admin': False}","{'url': 'https://api.github.com/repos/pandas-dev/pandas/issues/60624/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}",https://api.github.com/repos/pandas-dev/pandas/issues/60624/timeline,,
10,https://api.github.com/repos/pandas-dev/pandas/issues/60622,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas/issues/60622/labels{/name},https://api.github.com/repos/pandas-dev/pandas/issues/60622/comments,https://api.github.com/repos/pandas-dev/pandas/issues/60622/events,https://github.com/pandas-dev/pandas/pull/60622,2762534216,PR_kwDOAA0YD86GZgBA,60622,[WIP] `df.apply`: add support for `engine='bodo'`,"{'login': 'scott-routledge2', 'id': 171585127, 'node_id': 'U_kgDOCjouZw', 'avatar_url': 'https://avatars.githubusercontent.com/u/171585127?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/scott-routledge2', 'html_url': 'https://github.com/scott-routledge2', 'followers_url': 'https://api.github.com/users/scott-routledge2/followers', 'following_url': 'https://api.github.com/users/scott-routledge2/following{/other_user}', 'gists_url': 'https://api.github.com/users/scott-routledge2/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/scott-routledge2/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/scott-routledge2/subscriptions', 'organizations_url': 'https://api.github.com/users/scott-routledge2/orgs', 'repos_url': 'https://api.github.com/users/scott-routledge2/repos', 'events_url': 'https://api.github.com/users/scott-routledge2/events{/privacy}', 'received_events_url': 'https://api.github.com/users/scott-routledge2/received_events', 'type': 'User', 'user_view_type': 'public', 'site_admin': False}","[{'id': 219960758, 'node_id': 'MDU6TGFiZWwyMTk5NjA3NTg=', 'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/Needs%20Discussion', 'name': 'Needs Discussion', 'color': '207de5', 'default': False, 'description': 'Requires discussion from core team before further action'}]",open,False,,[],,2,2024-12-30T01:27:01Z,2024-12-31T15:43:31Z,,NONE,,True,"{'url': 'https://api.github.com/repos/pandas-dev/pandas/pulls/60622', 'html_url': 'https://github.com/pandas-dev/pandas/pull/60622', 'diff_url': 'https://github.com/pandas-dev/pandas/pull/60622.diff', 'patch_url': 'https://github.com/pandas-dev/pandas/pull/60622.patch', 'merged_at': None}","Adds support for specifying engine=""bodo"" when executing UDF's on DataFrames via `df.apply`.

- [ ] closes #xxxx (Replace xxxx with the GitHub issue number)
- [ ] [Tests added and passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#writing-tests) if fixing a bug or adding a new feature
- [ ] All [code checks passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#pre-commit).
- [ ] Added [type annotations](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#type-hints) to new arguments/methods/functions.
- [ ] Added an entry in the latest `doc/source/whatsnew/vX.X.X.rst` file if fixing a bug or adding a new feature.
",,"{'url': 'https://api.github.com/repos/pandas-dev/pandas/issues/60622/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}",https://api.github.com/repos/pandas-dev/pandas/issues/60622/timeline,,
11,https://api.github.com/repos/pandas-dev/pandas/issues/60618,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas/issues/60618/labels{/name},https://api.github.com/repos/pandas-dev/pandas/issues/60618/comments,https://api.github.com/repos/pandas-dev/pandas/issues/60618/events,https://github.com/pandas-dev/pandas/issues/60618,2762380604,I_kwDOAA0YD86kppU8,60618,ENH: native support for universal_pathlib (upath) IO,"{'login': 'zkurtz', 'id': 4934167, 'node_id': 'MDQ6VXNlcjQ5MzQxNjc=', 'avatar_url': 'https://avatars.githubusercontent.com/u/4934167?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/zkurtz', 'html_url': 'https://github.com/zkurtz', 'followers_url': 'https://api.github.com/users/zkurtz/followers', 'following_url': 'https://api.github.com/users/zkurtz/following{/other_user}', 'gists_url': 'https://api.github.com/users/zkurtz/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/zkurtz/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/zkurtz/subscriptions', 'organizations_url': 'https://api.github.com/users/zkurtz/orgs', 'repos_url': 'https://api.github.com/users/zkurtz/repos', 'events_url': 'https://api.github.com/users/zkurtz/events{/privacy}', 'received_events_url': 'https://api.github.com/users/zkurtz/received_events', 'type': 'User', 'user_view_type': 'public', 'site_admin': False}","[{'id': 76812, 'node_id': 'MDU6TGFiZWw3NjgxMg==', 'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/Enhancement', 'name': 'Enhancement', 'color': '4E9A06', 'default': False, 'description': None}, {'id': 1954720290, 'node_id': 'MDU6TGFiZWwxOTU0NzIwMjkw', 'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/Needs%20Triage', 'name': 'Needs Triage', 'color': '0052cc', 'default': False, 'description': 'Issue that has not been reviewed by a pandas team member'}]",open,False,,[],,0,2024-12-29T19:36:36Z,2024-12-29T19:36:50Z,,NONE,,,,"### Feature Type

- [X] Adding new functionality to pandas

- [ ] Changing existing functionality in pandas

- [ ] Removing existing functionality in pandas


### Problem Description

[universal_pathlib](https://github.com/fsspec/universal_pathlib) makes it quite a lot easier to read and write data frames directly against cloud paths like, say, `""s3://test_bucket/example.txt""` by absorbing authentication concerns and cloud-specific-implementation issues into to the construction of the path itself. This then allows IO methods to work as close to normally as possible without regard for the nature of the path being used (local vs GCS vs S3 etc.).

So, ideally, this would just work:
```
import pandas as pd
from upath import UPath

path = UPath(""s3://test_bucket/example.txt"")
[my data frame].to_parquet(path)
```

But it does not quite work. However, [this thin wrapper](https://github.com/zkurtz/dummio/blob/main/dummio/pandas/df_parquet.py) does seems to work, simply by detecting whether the input path is a UPath, and (if so) passing along the storage options into the pandas IO calls.

Proposal: Extend the allowable types of paths in pandas dataframe IO methods to include UPath, and automatically detect storage options in that case.

### Feature Description

Nothing to add ...

### Alternative Solutions

Nothing to add ...

### Additional Context

_No response_",,"{'url': 'https://api.github.com/repos/pandas-dev/pandas/issues/60618/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}",https://api.github.com/repos/pandas-dev/pandas/issues/60618/timeline,,
12,https://api.github.com/repos/pandas-dev/pandas/issues/60616,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas/issues/60616/labels{/name},https://api.github.com/repos/pandas-dev/pandas/issues/60616/comments,https://api.github.com/repos/pandas-dev/pandas/issues/60616/events,https://github.com/pandas-dev/pandas/issues/60616,2762344582,I_kwDOAA0YD86kpgiG,60616,ENH: RST support,"{'login': 'R5dan', 'id': 167037995, 'node_id': 'U_kgDOCfTMKw', 'avatar_url': 'https://avatars.githubusercontent.com/u/167037995?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/R5dan', 'html_url': 'https://github.com/R5dan', 'followers_url': 'https://api.github.com/users/R5dan/followers', 'following_url': 'https://api.github.com/users/R5dan/following{/other_user}', 'gists_url': 'https://api.github.com/users/R5dan/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/R5dan/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/R5dan/subscriptions', 'organizations_url': 'https://api.github.com/users/R5dan/orgs', 'repos_url': 'https://api.github.com/users/R5dan/repos', 'events_url': 'https://api.github.com/users/R5dan/events{/privacy}', 'received_events_url': 'https://api.github.com/users/R5dan/received_events', 'type': 'User', 'user_view_type': 'public', 'site_admin': False}","[{'id': 76812, 'node_id': 'MDU6TGFiZWw3NjgxMg==', 'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/Enhancement', 'name': 'Enhancement', 'color': '4E9A06', 'default': False, 'description': None}, {'id': 1954720290, 'node_id': 'MDU6TGFiZWwxOTU0NzIwMjkw', 'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/Needs%20Triage', 'name': 'Needs Triage', 'color': '0052cc', 'default': False, 'description': 'Issue that has not been reviewed by a pandas team member'}]",open,False,,[],,0,2024-12-29T17:41:50Z,2024-12-30T00:48:45Z,,NONE,,,,"### Feature Type

- [X] Adding new functionality to pandas

- [ ] Changing existing functionality in pandas

- [ ] Removing existing functionality in pandas


### Problem Description

I wish I could use ReStructured Text with pandas

### Feature Description

The end users code:

```python
import pandas as pd
df=pd.read_rst(rst)
df.to_rst()
```

I believe tabulate has a way to do this.

### Alternative Solutions

I also built a way to make rst tables.

### Additional Context

- [The RST docs](https://docutils.sourceforge.io/docs/ref/rst/restructuredtext.html#tables)

I think `Grid Tables` would be best for pandas (or `Simple Tables`)

I did not use sudo-code in the examples due to complexity and that examples of how to do this can be seen in the above packages. See RST docs for what they look like.",,"{'url': 'https://api.github.com/repos/pandas-dev/pandas/issues/60616/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}",https://api.github.com/repos/pandas-dev/pandas/issues/60616/timeline,,
13,https://api.github.com/repos/pandas-dev/pandas/issues/60613,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas/issues/60613/labels{/name},https://api.github.com/repos/pandas-dev/pandas/issues/60613/comments,https://api.github.com/repos/pandas-dev/pandas/issues/60613/events,https://github.com/pandas-dev/pandas/pull/60613,2761745441,PR_kwDOAA0YD86GW84l,60613,ENH: Make print_thing respect display.precision for Real numbers,"{'login': 'aydinomer00', 'id': 109145643, 'node_id': 'U_kgDOBoFuKw', 'avatar_url': 'https://avatars.githubusercontent.com/u/109145643?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/aydinomer00', 'html_url': 'https://github.com/aydinomer00', 'followers_url': 'https://api.github.com/users/aydinomer00/followers', 'following_url': 'https://api.github.com/users/aydinomer00/following{/other_user}', 'gists_url': 'https://api.github.com/users/aydinomer00/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/aydinomer00/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/aydinomer00/subscriptions', 'organizations_url': 'https://api.github.com/users/aydinomer00/orgs', 'repos_url': 'https://api.github.com/users/aydinomer00/repos', 'events_url': 'https://api.github.com/users/aydinomer00/events{/privacy}', 'received_events_url': 'https://api.github.com/users/aydinomer00/received_events', 'type': 'User', 'user_view_type': 'public', 'site_admin': False}","[{'id': 76812, 'node_id': 'MDU6TGFiZWw3NjgxMg==', 'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/Enhancement', 'name': 'Enhancement', 'color': '4E9A06', 'default': False, 'description': None}, {'id': 13101118, 'node_id': 'MDU6TGFiZWwxMzEwMTExOA==', 'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/Output-Formatting', 'name': 'Output-Formatting', 'color': 'ededed', 'default': False, 'description': '__repr__ of pandas objects, to_string'}]",open,False,,[],,0,2024-12-28T14:35:58Z,2024-12-31T10:11:25Z,,NONE,,False,"{'url': 'https://api.github.com/repos/pandas-dev/pandas/pulls/60613', 'html_url': 'https://github.com/pandas-dev/pandas/pull/60613', 'diff_url': 'https://github.com/pandas-dev/pandas/pull/60613.diff', 'patch_url': 'https://github.com/pandas-dev/pandas/pull/60613.patch', 'merged_at': None}","- [x] closes #60503

- [x] Tests added and passed:
  - Added test_pprint_thing_real_precision to test precision formatting
  - Verified with multiple display.precision values (2, 3, 4)
  - Tested with various float numbers including np.pi

- [x] All code checks passed

- [x] Added type annotations for clarity in modified functions

- [x] Added an entry in the latest doc/source/whatsnew/vX.X.X.rst file:
      - Enhanced print_thing to respect display.precision setting for Real numbers

This PR modifies the print_thing function to respect display.precision settings when formatting Real numbers. For example:

```python
with pd.option_context('display.precision', 2):
    df = pd.DataFrame({""value"": [np.pi]})
    print(df)  # Shows 3.14

with pd.option_context('display.precision', 4):
    print(df)  # Shows 3.1416",,"{'url': 'https://api.github.com/repos/pandas-dev/pandas/issues/60613/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}",https://api.github.com/repos/pandas-dev/pandas/issues/60613/timeline,,
14,https://api.github.com/repos/pandas-dev/pandas/issues/60612,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas/issues/60612/labels{/name},https://api.github.com/repos/pandas-dev/pandas/issues/60612/comments,https://api.github.com/repos/pandas-dev/pandas/issues/60612/events,https://github.com/pandas-dev/pandas/pull/60612,2761308914,PR_kwDOAA0YD86GVfKN,60612,DOC: Adding a Persian version of Pandas Cheat Sheet,"{'login': 'HasssanRad', 'id': 115450900, 'node_id': 'U_kgDOBuGkFA', 'avatar_url': 'https://avatars.githubusercontent.com/u/115450900?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/HasssanRad', 'html_url': 'https://github.com/HasssanRad', 'followers_url': 'https://api.github.com/users/HasssanRad/followers', 'following_url': 'https://api.github.com/users/HasssanRad/following{/other_user}', 'gists_url': 'https://api.github.com/users/HasssanRad/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/HasssanRad/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/HasssanRad/subscriptions', 'organizations_url': 'https://api.github.com/users/HasssanRad/orgs', 'repos_url': 'https://api.github.com/users/HasssanRad/repos', 'events_url': 'https://api.github.com/users/HasssanRad/events{/privacy}', 'received_events_url': 'https://api.github.com/users/HasssanRad/received_events', 'type': 'User', 'user_view_type': 'public', 'site_admin': False}","[{'id': 134699, 'node_id': 'MDU6TGFiZWwxMzQ2OTk=', 'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/Docs', 'name': 'Docs', 'color': '3465A4', 'default': False, 'description': None}]",open,False,,[],,1,2024-12-27T22:11:25Z,2024-12-31T11:15:40Z,,NONE,,False,"{'url': 'https://api.github.com/repos/pandas-dev/pandas/pulls/60612', 'html_url': 'https://github.com/pandas-dev/pandas/pull/60612', 'diff_url': 'https://github.com/pandas-dev/pandas/pull/60612.diff', 'patch_url': 'https://github.com/pandas-dev/pandas/pull/60612.patch', 'merged_at': None}","I have translated the Pandas cheat sheet for the Persian-speaking community around the world, and it is ready to be added to the Pandas project documentation.",,"{'url': 'https://api.github.com/repos/pandas-dev/pandas/issues/60612/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}",https://api.github.com/repos/pandas-dev/pandas/issues/60612/timeline,,
15,https://api.github.com/repos/pandas-dev/pandas/issues/60611,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas/issues/60611/labels{/name},https://api.github.com/repos/pandas-dev/pandas/issues/60611/comments,https://api.github.com/repos/pandas-dev/pandas/issues/60611/events,https://github.com/pandas-dev/pandas/issues/60611,2761261969,I_kwDOAA0YD86klYOR,60611,"BUG: Segfault on `np.maximum(series, ...)`","{'login': 'ssche', 'id': 7367411, 'node_id': 'MDQ6VXNlcjczNjc0MTE=', 'avatar_url': 'https://avatars.githubusercontent.com/u/7367411?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/ssche', 'html_url': 'https://github.com/ssche', 'followers_url': 'https://api.github.com/users/ssche/followers', 'following_url': 'https://api.github.com/users/ssche/following{/other_user}', 'gists_url': 'https://api.github.com/users/ssche/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/ssche/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/ssche/subscriptions', 'organizations_url': 'https://api.github.com/users/ssche/orgs', 'repos_url': 'https://api.github.com/users/ssche/repos', 'events_url': 'https://api.github.com/users/ssche/events{/privacy}', 'received_events_url': 'https://api.github.com/users/ssche/received_events', 'type': 'User', 'user_view_type': 'public', 'site_admin': False}","[{'id': 76811, 'node_id': 'MDU6TGFiZWw3NjgxMQ==', 'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/Bug', 'name': 'Bug', 'color': 'e10c02', 'default': False, 'description': None}, {'id': 32815646, 'node_id': 'MDU6TGFiZWwzMjgxNTY0Ng==', 'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/Regression', 'name': 'Regression', 'color': 'e11d21', 'default': False, 'description': 'Functionality that used to work in a prior pandas version'}, {'id': 3660542278, 'node_id': 'LA_kwDOAA0YD87aL3FG', 'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/ufuncs', 'name': 'ufuncs', 'color': 'bfdadc', 'default': False, 'description': '__array_ufunc__ and __array_function__'}]",open,False,,[],,4,2024-12-27T20:48:32Z,2024-12-29T12:52:05Z,,CONTRIBUTOR,,,,"### Pandas version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pandas.pydata.org/docs/whatsnew/index.html) of pandas.

- [ ] I have confirmed this bug exists on the [main branch](https://pandas.pydata.org/docs/dev/getting_started/install.html#installing-the-development-version-of-pandas) of pandas.


### Reproducible Example

```python
import numpy as np
import pandas as pd
a = [-3.22, 4]
x = pd.Series(a)
np.maximum(x, 0, where=x > 2)
```



### Issue Description

`Segmentation fault (core dumped)` when executing above code.

`np.maximum(...)` goes into an infinite call cycle which eventually exceeds the max. stack size.

Call stack (bottom up):

```
...
array_ufunc, arraylike.py:399
__array_ufunc__, generic.py:2171
array_ufunc, arraylike.py:399
__array_ufunc__, generic.py:2171
array_ufunc, arraylike.py:399
__array_ufunc__, generic.py:2171
```



### `__array_ufunc__, generic.py:2171` (`core/generic.py`):

```
class NDFrame
    ...
    @final
    def __array_ufunc__(
        self, ufunc: np.ufunc, method: str, *inputs: Any, **kwargs: Any
    ):
        return arraylike.array_ufunc(self, ufunc, method, *inputs, **kwargs)  <--

```

### `array_ufunc, arraylike.py:399` (`core/arraylike.py`):

```

    elif self.ndim == 1:
        # ufunc(series, ...)
        inputs = tuple(extract_array(x, extract_numpy=True) for x in inputs)
        result = getattr(ufunc, method)(*inputs, **kwargs)   <--
    else:
        # ufunc(dataframe)
        if method == ""__call__"" and not kwargs:
```

### Expected Behavior

No recursion and successful execution of code. This used to work fine in `pandas==2.1.1` (or perhaps even higher).

### Installed Versions

<details>

INSTALLED VERSIONS
------------------
commit                : 0691c5cf90477d3503834d983f69350f250a6ff7
python                : 3.13.1
python-bits           : 64
OS                    : Linux
OS-release            : 6.12.5-200.fc41.x86_64
Version               : #1 SMP PREEMPT_DYNAMIC Sun Dec 15 16:48:23 UTC 2024
machine               : x86_64
processor             : 
byteorder             : little
LC_ALL                : None
LANG                  : en_AU.UTF-8
LOCALE                : en_AU.UTF-8

pandas                : 2.2.3
numpy                 : 2.2.1
pytz                  : 2020.4
dateutil              : 2.9.0.post0
pip                   : 24.3.1
Cython                : 3.0.11
sphinx                : None
IPython               : None
adbc-driver-postgresql: None
adbc-driver-sqlite    : None
bs4                   : None
blosc                 : None
bottleneck            : 1.4.2
dataframe-api-compat  : None
fastparquet           : None
fsspec                : None
html5lib              : None
hypothesis            : None
gcsfs                 : None
jinja2                : None
lxml.etree            : None
matplotlib            : None
numba                 : None
numexpr               : 2.10.2
odfpy                 : None
openpyxl              : 3.1.2
pandas_gbq            : None
psycopg2              : 2.9.10
pymysql               : None
pyarrow               : 18.1.0
pyreadstat            : None
pytest                : 8.3.4
python-calamine       : None
pyxlsb                : None
s3fs                  : None
scipy                 : 1.14.1
sqlalchemy            : None
tables                : 3.10.1
tabulate              : None
xarray                : None
xlrd                  : 2.0.1
xlsxwriter            : None
zstandard             : None
tzdata                : 2024.2
qtpy                  : None
pyqt5                 : None


</details>
",,"{'url': 'https://api.github.com/repos/pandas-dev/pandas/issues/60611/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}",https://api.github.com/repos/pandas-dev/pandas/issues/60611/timeline,,
16,https://api.github.com/repos/pandas-dev/pandas/issues/60609,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas/issues/60609/labels{/name},https://api.github.com/repos/pandas-dev/pandas/issues/60609/comments,https://api.github.com/repos/pandas-dev/pandas/issues/60609/events,https://github.com/pandas-dev/pandas/issues/60609,2760024766,I_kwDOAA0YD86kgqK-,60609,to_sql doesn't seem to allow upload of df with some columns when the target table has a calculated column,"{'login': 'qzoxec', 'id': 2993211, 'node_id': 'MDQ6VXNlcjI5OTMyMTE=', 'avatar_url': 'https://avatars.githubusercontent.com/u/2993211?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/qzoxec', 'html_url': 'https://github.com/qzoxec', 'followers_url': 'https://api.github.com/users/qzoxec/followers', 'following_url': 'https://api.github.com/users/qzoxec/following{/other_user}', 'gists_url': 'https://api.github.com/users/qzoxec/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/qzoxec/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/qzoxec/subscriptions', 'organizations_url': 'https://api.github.com/users/qzoxec/orgs', 'repos_url': 'https://api.github.com/users/qzoxec/repos', 'events_url': 'https://api.github.com/users/qzoxec/events{/privacy}', 'received_events_url': 'https://api.github.com/users/qzoxec/received_events', 'type': 'User', 'user_view_type': 'public', 'site_admin': False}",[],open,False,,[],,2,2024-12-26T18:14:51Z,2024-12-28T23:28:22Z,,NONE,,,,"I am trying to append a dataframe with several columns to a MS SQL table with a calculated field. I get the following error on attempt: 
""sqlalchemy.exc.ProgrammingError: (pyodbc.ProgrammingError) ('42000', '[42000] [Microsoft][ODBC Driver 17 for SQL Server][SQL Server]The column ""Fieldname"" cannot be modified because it is either a computed column or is the result of a UNION operator. (271) (SQLExecDirectW); [42000] [Microsoft][ODBC Driver 17 for SQL Server][SQL Server]Statement(s) could not be prepared. (8180)')""

This issue seems to have been addressed in the AWS sdk using the use_column_names parameter. See here - https://github.com/aws/aws-sdk-pandas/issues/2170 

That parameter doesn't seem to exist when using a sqlalchemy pyodbc connection. - ""TypeError: to_sql() got an unexpected keyword argument 'use_column_names'""

Is there something similar that exists for a sqlalchemy pyodbc connection? ",,"{'url': 'https://api.github.com/repos/pandas-dev/pandas/issues/60609/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}",https://api.github.com/repos/pandas-dev/pandas/issues/60609/timeline,,
17,https://api.github.com/repos/pandas-dev/pandas/issues/60608,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas/issues/60608/labels{/name},https://api.github.com/repos/pandas-dev/pandas/issues/60608/comments,https://api.github.com/repos/pandas-dev/pandas/issues/60608/events,https://github.com/pandas-dev/pandas/pull/60608,2759892964,PR_kwDOAA0YD86GQxw8,60608,DOC: Add Hugging Face Hub access,"{'login': 'lhoestq', 'id': 42851186, 'node_id': 'MDQ6VXNlcjQyODUxMTg2', 'avatar_url': 'https://avatars.githubusercontent.com/u/42851186?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/lhoestq', 'html_url': 'https://github.com/lhoestq', 'followers_url': 'https://api.github.com/users/lhoestq/followers', 'following_url': 'https://api.github.com/users/lhoestq/following{/other_user}', 'gists_url': 'https://api.github.com/users/lhoestq/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/lhoestq/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/lhoestq/subscriptions', 'organizations_url': 'https://api.github.com/users/lhoestq/orgs', 'repos_url': 'https://api.github.com/users/lhoestq/repos', 'events_url': 'https://api.github.com/users/lhoestq/events{/privacy}', 'received_events_url': 'https://api.github.com/users/lhoestq/received_events', 'type': 'User', 'user_view_type': 'public', 'site_admin': False}","[{'id': 134699, 'node_id': 'MDU6TGFiZWwxMzQ2OTk=', 'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/Docs', 'name': 'Docs', 'color': '3465A4', 'default': False, 'description': None}]",open,False,,[],,1,2024-12-26T15:32:30Z,2024-12-31T17:51:22Z,,NONE,,False,"{'url': 'https://api.github.com/repos/pandas-dev/pandas/pulls/60608', 'html_url': 'https://github.com/pandas-dev/pandas/pull/60608', 'diff_url': 'https://github.com/pandas-dev/pandas/pull/60608.diff', 'patch_url': 'https://github.com/pandas-dev/pandas/pull/60608.patch', 'merged_at': None}","Hi team ! We recently made most of the 200k+ datasets from the community on Hugging Face loadable in pandas :)
And we even show the code snippet to load a dataset on each dataset page (see images below)

In this PR I added documentation on accessing Hugging Face Datasets using `fsspec`. It uses `hf://` paths and the implementation is part of the `huggingface-hub` library. Let me know what you think !


1. ""Use this dataset"" button on a dataset page:
<img width=""1290"" alt=""image"" src=""https://github.com/user-attachments/assets/6ab57ddf-c42d-4892-8572-6bd0e772e7ce"" />

2. Modal showing [pandas code snippet](https://huggingface.co/datasets/google/FACTS-grounding-public?library=pandas):
<img width=""1294"" alt=""image"" src=""https://github.com/user-attachments/assets/c08ca12f-3b98-4748-8569-8d71892234c3"" />

closes https://github.com/pandas-dev/pandas/issues/46000
",,"{'url': 'https://api.github.com/repos/pandas-dev/pandas/issues/60608/reactions', 'total_count': 6, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 3, 'confused': 0, 'heart': 3, 'rocket': 0, 'eyes': 0}",https://api.github.com/repos/pandas-dev/pandas/issues/60608/timeline,,
18,https://api.github.com/repos/pandas-dev/pandas/issues/60603,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas/issues/60603/labels{/name},https://api.github.com/repos/pandas-dev/pandas/issues/60603/comments,https://api.github.com/repos/pandas-dev/pandas/issues/60603/events,https://github.com/pandas-dev/pandas/issues/60603,2758345288,I_kwDOAA0YD86kaQJI,60603,BUG: Dropped Index Name on Aggregated Index Column with MultiIndexed DataFrame,"{'login': 'RahimD', 'id': 46304915, 'node_id': 'MDQ6VXNlcjQ2MzA0OTE1', 'avatar_url': 'https://avatars.githubusercontent.com/u/46304915?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/RahimD', 'html_url': 'https://github.com/RahimD', 'followers_url': 'https://api.github.com/users/RahimD/followers', 'following_url': 'https://api.github.com/users/RahimD/following{/other_user}', 'gists_url': 'https://api.github.com/users/RahimD/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/RahimD/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/RahimD/subscriptions', 'organizations_url': 'https://api.github.com/users/RahimD/orgs', 'repos_url': 'https://api.github.com/users/RahimD/repos', 'events_url': 'https://api.github.com/users/RahimD/events{/privacy}', 'received_events_url': 'https://api.github.com/users/RahimD/received_events', 'type': 'User', 'user_view_type': 'public', 'site_admin': False}","[{'id': 76811, 'node_id': 'MDU6TGFiZWw3NjgxMQ==', 'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/Bug', 'name': 'Bug', 'color': 'e10c02', 'default': False, 'description': None}, {'id': 233160, 'node_id': 'MDU6TGFiZWwyMzMxNjA=', 'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/Groupby', 'name': 'Groupby', 'color': '729FCF', 'default': False, 'description': None}, {'id': 2365504893, 'node_id': 'MDU6TGFiZWwyMzY1NTA0ODkz', 'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/Closing%20Candidate', 'name': 'Closing Candidate', 'color': 'be21f2', 'default': False, 'description': 'May be closeable, needs more eyeballs'}]",open,False,,[],,1,2024-12-24T23:07:41Z,2024-12-26T22:02:54Z,,NONE,,,,"### Pandas version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pandas.pydata.org/docs/whatsnew/index.html) of pandas.

- [X] I have confirmed this bug exists on the [main branch](https://pandas.pydata.org/docs/dev/getting_started/install.html#installing-the-development-version-of-pandas) of pandas.


### Reproducible Example

```python
df = pandas.DataFrame({""A"" : [1,2,3,1,2,3], ""B"": [4,5,6,4,5,6], ""C"" : [7,8,9,7,8,9]})
df = df.set_index(['A', 'B'])
df.groupby(lambda x : x[0]).aggregate('sum')
```


### Issue Description

When using a lambda to group a DataFrame by, even though the lambda is using a pre-existing index from the DataFrame, the resulting index in the aggregation does not take its name. Comparatively, using ```df.groupby('A')``` in the above example would yield an index with the index name 'A'.  As best as I can tell, this happens because of [this](https://github.com/pandas-dev/pandas/blob/8a5344742c5165b2595f7ccca9e17d5eff7f7886/pandas/core/groupby/ops.py#L766), which requests ```name[0]``` from the ```BaseGrouper``` object, which ultimately seems to get its names from the underlying ```Grouping``` object. However, when getting that [name](https://github.com/pandas-dev/pandas/blob/8a5344742c5165b2595f7ccca9e17d5eff7f7886/pandas/core/groupby/grouper.py#L550), since ```self.grouping_vector``` is a ```MultiIndex```, the ```elif isinstance(self.grouping_vector, Index):``` branch is taken, which leads to a request for the ```.name``` attribute of a ```MultiIndex```, which returns ```None```. This  names of index columns are dropped even if a list of lambdas is provided in order to produce multiple levels of a MultiIndex in the aggregation output, i.e. even if ```len(self.groupings) > 1``` in the ```BaseGrouper``` object

Apologies in advance if this is intended behaviour.

### Expected Behavior

```python
df = pandas.DataFrame({""A"" : [1,2,3,1,2,3], ""B"": [4,5,6,4,5,6], ""C"" : [7,8,9,7,8,9]})
df = df.set_index(['A', 'B'])
df.groupby('A')
```

### Installed Versions

<details>

INSTALLED VERSIONS
------------------
commit                : 0691c5cf90477d3503834d983f69350f250a6ff7
python                : 3.13.1
python-bits           : 64
OS                    : Windows
OS-release            : 10
Version               : 10.0.18363
machine               : AMD64
processor             : AMD64 Family 21 Model 96 Stepping 1, AuthenticAMD
byteorder             : little
LC_ALL                : None
LANG                  : None
LOCALE                : English_Canada.1252

pandas                : 2.2.3
numpy                 : 2.2.1
pytz                  : 2024.2
dateutil              : 2.9.0.post0
pip                   : 24.3.1
Cython                : None
sphinx                : None
IPython               : None
adbc-driver-postgresql: None
adbc-driver-sqlite    : None
bs4                   : None
blosc                 : None
bottleneck            : None
dataframe-api-compat  : None
fastparquet           : None
fsspec                : None
html5lib              : None
hypothesis            : None
gcsfs                 : None
jinja2                : None
lxml.etree            : None
matplotlib            : None
numba                 : None
numexpr               : None
odfpy                 : None
openpyxl              : None
pandas_gbq            : None
psycopg2              : None
pymysql               : None
pyarrow               : None
pyreadstat            : None
pytest                : None
python-calamine       : None
pyxlsb                : None
s3fs                  : None
scipy                 : None
sqlalchemy            : None
tables                : None
tabulate              : None
xarray                : None
xlrd                  : None
xlsxwriter            : None
zstandard             : None
tzdata                : 2024.2
qtpy                  : None
pyqt5                 : None

</details>
",,"{'url': 'https://api.github.com/repos/pandas-dev/pandas/issues/60603/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}",https://api.github.com/repos/pandas-dev/pandas/issues/60603/timeline,,
19,https://api.github.com/repos/pandas-dev/pandas/issues/60600,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas/issues/60600/labels{/name},https://api.github.com/repos/pandas-dev/pandas/issues/60600/comments,https://api.github.com/repos/pandas-dev/pandas/issues/60600/events,https://github.com/pandas-dev/pandas/issues/60600,2756860713,I_kwDOAA0YD86kUlsp,60600,BUG: loc[] returns object type instead of float,"{'login': 'metazoic', 'id': 39023576, 'node_id': 'MDQ6VXNlcjM5MDIzNTc2', 'avatar_url': 'https://avatars.githubusercontent.com/u/39023576?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/metazoic', 'html_url': 'https://github.com/metazoic', 'followers_url': 'https://api.github.com/users/metazoic/followers', 'following_url': 'https://api.github.com/users/metazoic/following{/other_user}', 'gists_url': 'https://api.github.com/users/metazoic/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/metazoic/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/metazoic/subscriptions', 'organizations_url': 'https://api.github.com/users/metazoic/orgs', 'repos_url': 'https://api.github.com/users/metazoic/repos', 'events_url': 'https://api.github.com/users/metazoic/events{/privacy}', 'received_events_url': 'https://api.github.com/users/metazoic/received_events', 'type': 'User', 'user_view_type': 'public', 'site_admin': False}","[{'id': 76811, 'node_id': 'MDU6TGFiZWw3NjgxMQ==', 'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/Bug', 'name': 'Bug', 'color': 'e10c02', 'default': False, 'description': None}, {'id': 2822098, 'node_id': 'MDU6TGFiZWwyODIyMDk4', 'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/Indexing', 'name': 'Indexing', 'color': '0b02e1', 'default': False, 'description': 'Related to indexing on series/frames, not to indexes themselves'}, {'id': 31404521, 'node_id': 'MDU6TGFiZWwzMTQwNDUyMQ==', 'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/Dtype%20Conversions', 'name': 'Dtype Conversions', 'color': 'e102d8', 'default': False, 'description': 'Unexpected or buggy dtype conversions'}]",open,False,"{'login': 'parthi-siva', 'id': 25401444, 'node_id': 'MDQ6VXNlcjI1NDAxNDQ0', 'avatar_url': 'https://avatars.githubusercontent.com/u/25401444?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/parthi-siva', 'html_url': 'https://github.com/parthi-siva', 'followers_url': 'https://api.github.com/users/parthi-siva/followers', 'following_url': 'https://api.github.com/users/parthi-siva/following{/other_user}', 'gists_url': 'https://api.github.com/users/parthi-siva/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/parthi-siva/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/parthi-siva/subscriptions', 'organizations_url': 'https://api.github.com/users/parthi-siva/orgs', 'repos_url': 'https://api.github.com/users/parthi-siva/repos', 'events_url': 'https://api.github.com/users/parthi-siva/events{/privacy}', 'received_events_url': 'https://api.github.com/users/parthi-siva/received_events', 'type': 'User', 'user_view_type': 'public', 'site_admin': False}","[{'login': 'parthi-siva', 'id': 25401444, 'node_id': 'MDQ6VXNlcjI1NDAxNDQ0', 'avatar_url': 'https://avatars.githubusercontent.com/u/25401444?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/parthi-siva', 'html_url': 'https://github.com/parthi-siva', 'followers_url': 'https://api.github.com/users/parthi-siva/followers', 'following_url': 'https://api.github.com/users/parthi-siva/following{/other_user}', 'gists_url': 'https://api.github.com/users/parthi-siva/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/parthi-siva/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/parthi-siva/subscriptions', 'organizations_url': 'https://api.github.com/users/parthi-siva/orgs', 'repos_url': 'https://api.github.com/users/parthi-siva/repos', 'events_url': 'https://api.github.com/users/parthi-siva/events{/privacy}', 'received_events_url': 'https://api.github.com/users/parthi-siva/received_events', 'type': 'User', 'user_view_type': 'public', 'site_admin': False}, {'login': 'DarthKitten2130', 'id': 72032381, 'node_id': 'MDQ6VXNlcjcyMDMyMzgx', 'avatar_url': 'https://avatars.githubusercontent.com/u/72032381?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/DarthKitten2130', 'html_url': 'https://github.com/DarthKitten2130', 'followers_url': 'https://api.github.com/users/DarthKitten2130/followers', 'following_url': 'https://api.github.com/users/DarthKitten2130/following{/other_user}', 'gists_url': 'https://api.github.com/users/DarthKitten2130/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/DarthKitten2130/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/DarthKitten2130/subscriptions', 'organizations_url': 'https://api.github.com/users/DarthKitten2130/orgs', 'repos_url': 'https://api.github.com/users/DarthKitten2130/repos', 'events_url': 'https://api.github.com/users/DarthKitten2130/events{/privacy}', 'received_events_url': 'https://api.github.com/users/DarthKitten2130/received_events', 'type': 'User', 'user_view_type': 'public', 'site_admin': False}]",,3,2024-12-23T23:43:44Z,2024-12-30T17:55:52Z,,NONE,,,,"### Pandas version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pandas.pydata.org/docs/whatsnew/index.html) of pandas.

- [X] I have confirmed this bug exists on the [main branch](https://pandas.pydata.org/docs/dev/getting_started/install.html#installing-the-development-version-of-pandas) of pandas.


### Reproducible Example

```python
import pandas as pd
df = pd.DataFrame([['a',1.,2.],['b',3.,4.]])
df.loc[0,[1,2]].dtypes
df[[1,2]].loc[0].dtypes
```


### Issue Description

`df.loc[0,[1,2]]` results in a Series of type `dtype('O')`, while `df[[1,2]].loc[0]` results in a Series of type `dtype('float64')`.

### Expected Behavior

I would expect `df.loc[0,[1,2]]` to be of type `float64`, same as `df[[1,2]].loc[0]`. The current behavior seems to encourage chaining instead of canonical referencing.

### Installed Versions

<details>

INSTALLED VERSIONS
------------------
commit                : 0691c5cf90477d3503834d983f69350f250a6ff7
python                : 3.12.8
python-bits           : 64
OS                    : Darwin
OS-release            : 23.6.0
Version               : Darwin Kernel Version 23.6.0: Thu Sep 12 23:35:10 PDT 2024; root:xnu-10063.141.1.701.1~1/RELEASE_ARM64_T6030
machine               : arm64
processor             : arm
byteorder             : little
LC_ALL                : None
LANG                  : en_US.UTF-8
LOCALE                : en_US.UTF-8

pandas                : 2.2.3
numpy                 : 1.26.4
pytz                  : 2024.1
dateutil              : 2.9.0.post0
pip                   : 24.3.1
Cython                : None
sphinx                : 8.1.3
IPython               : None
adbc-driver-postgresql: None
adbc-driver-sqlite    : None
bs4                   : 4.12.3
blosc                 : None
bottleneck            : 1.4.2
dataframe-api-compat  : None
fastparquet           : None
fsspec                : 2024.12.0
html5lib              : 1.1
hypothesis            : None
gcsfs                 : None
jinja2                : 3.1.5
lxml.etree            : 5.3.0
matplotlib            : 3.10.0
numba                 : 0.60.0
numexpr               : 2.10.2
odfpy                 : None
openpyxl              : 3.1.5
pandas_gbq            : None
psycopg2              : None
pymysql               : None
pyarrow               : 18.1.0
pyreadstat            : None
pytest                : 8.3.4
python-calamine       : None
pyxlsb                : None
s3fs                  : 2024.12.0
scipy                 : 1.14.1
sqlalchemy            : 2.0.36
tables                : 3.10.1
tabulate              : 0.9.0
xarray                : 2024.11.0
xlrd                  : None
xlsxwriter            : None
zstandard             : 0.23.0
tzdata                : 2024.2
qtpy                  : N/A
pyqt5                 : None

</details>
",,"{'url': 'https://api.github.com/repos/pandas-dev/pandas/issues/60600/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}",https://api.github.com/repos/pandas-dev/pandas/issues/60600/timeline,,
20,https://api.github.com/repos/pandas-dev/pandas/issues/60596,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas/issues/60596/labels{/name},https://api.github.com/repos/pandas-dev/pandas/issues/60596/comments,https://api.github.com/repos/pandas-dev/pandas/issues/60596/events,https://github.com/pandas-dev/pandas/issues/60596,2753609672,I_kwDOAA0YD86kIL_I,60596,BUG: unable to generate daily business frequency data,"{'login': 'ngupta23', 'id': 33585645, 'node_id': 'MDQ6VXNlcjMzNTg1NjQ1', 'avatar_url': 'https://avatars.githubusercontent.com/u/33585645?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/ngupta23', 'html_url': 'https://github.com/ngupta23', 'followers_url': 'https://api.github.com/users/ngupta23/followers', 'following_url': 'https://api.github.com/users/ngupta23/following{/other_user}', 'gists_url': 'https://api.github.com/users/ngupta23/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/ngupta23/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/ngupta23/subscriptions', 'organizations_url': 'https://api.github.com/users/ngupta23/orgs', 'repos_url': 'https://api.github.com/users/ngupta23/repos', 'events_url': 'https://api.github.com/users/ngupta23/events{/privacy}', 'received_events_url': 'https://api.github.com/users/ngupta23/received_events', 'type': 'User', 'user_view_type': 'public', 'site_admin': False}","[{'id': 34444536, 'node_id': 'MDU6TGFiZWwzNDQ0NDUzNg==', 'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/Usage%20Question', 'name': 'Usage Question', 'color': '0052cc', 'default': False, 'description': None}, {'id': 53181044, 'node_id': 'MDU6TGFiZWw1MzE4MTA0NA==', 'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/Frequency', 'name': 'Frequency', 'color': '0052cc', 'default': False, 'description': 'DateOffsets'}, {'id': 307649777, 'node_id': 'MDU6TGFiZWwzMDc2NDk3Nzc=', 'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/Needs%20Info', 'name': 'Needs Info', 'color': '207de5', 'default': False, 'description': 'Clarification about behavior needed to assess issue'}]",open,False,,[],,2,2024-12-20T23:02:10Z,2024-12-30T17:30:15Z,,NONE,,,,"### Pandas version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pandas.pydata.org/docs/whatsnew/index.html) of pandas.

- [ ] I have confirmed this bug exists on the [main branch](https://pandas.pydata.org/docs/dev/getting_started/install.html#installing-the-development-version-of-pandas) of pandas.


### Reproducible Example

```python
import pandas as pd
pd.date_range('2000-01-03 00:00:00', freq=pd.offsets.BusinessHour(start='00:00', end='23:59'), periods=25)

DatetimeIndex(['2000-01-03 00:00:00', '2000-01-03 01:00:00',
               '2000-01-03 02:00:00', '2000-01-03 03:00:00',
               '2000-01-03 04:00:00', '2000-01-03 05:00:00',
               '2000-01-03 06:00:00', '2000-01-03 07:00:00',
               '2000-01-03 08:00:00', '2000-01-03 09:00:00',
               '2000-01-03 10:00:00', '2000-01-03 11:00:00',
               '2000-01-03 12:00:00', '2000-01-03 13:00:00',
               '2000-01-03 14:00:00', '2000-01-03 15:00:00',
               '2000-01-03 16:00:00', '2000-01-03 17:00:00',
               '2000-01-03 18:00:00', '2000-01-03 19:00:00',
               '2000-01-03 20:00:00', '2000-01-03 21:00:00',
               '2000-01-03 22:00:00', '2000-01-03 23:00:00',
               '2000-01-04 00:01:00'],
              dtype='datetime64[ns]', freq='BH')
```


### Issue Description

I have a time series dataset that produces data every hour from Monday to Friday and no data on Saturday and Sunday. I am unable to create these time stamps using `pd.offsets.BusinessHour`. There is an issue with the crossover between days. As you can see above, the timestamp 2000-01-04 00:00:00 is completely missing.

If this is not a bug, could anyone please let me know how to produce these time indices.

### Expected Behavior

```
DatetimeIndex(['2000-01-03 00:00:00', '2000-01-03 01:00:00',
               '2000-01-03 02:00:00', '2000-01-03 03:00:00',
               '2000-01-03 04:00:00', '2000-01-03 05:00:00',
               '2000-01-03 06:00:00', '2000-01-03 07:00:00',
               '2000-01-03 08:00:00', '2000-01-03 09:00:00',
               '2000-01-03 10:00:00', '2000-01-03 11:00:00',
               '2000-01-03 12:00:00', '2000-01-03 13:00:00',
               '2000-01-03 14:00:00', '2000-01-03 15:00:00',
               '2000-01-03 16:00:00', '2000-01-03 17:00:00',
               '2000-01-03 18:00:00', '2000-01-03 19:00:00',
               '2000-01-03 20:00:00', '2000-01-03 21:00:00',
               '2000-01-03 22:00:00', '2000-01-03 23:00:00',
               '2000-01-04 00:00:00'],
              dtype='datetime64[ns]', freq='BH')
```

**Timestamp '2000-01-04 00:00:00' should be present.**

### Installed Versions

<details>

INSTALLED VERSIONS
------------------
commit              : a671b5a8bf5dd13fb19f0e88edc679bc9e15c673
python              : 3.10.12.final.0
python-bits         : 64
OS                  : Linux
OS-release          : 5.15.146.1-microsoft-standard-WSL2
Version             : #1 SMP Thu Jan 11 04:09:03 UTC 2024
machine             : x86_64
processor           : x86_64
byteorder           : little
LC_ALL              : None
LANG                : C.UTF-8
LOCALE              : en_US.UTF-8

pandas              : 2.1.4
numpy               : 1.26.4
pytz                : 2024.2
dateutil            : 2.9.0.post0
setuptools          : 69.5.1
pip                 : None
Cython              : None
pytest              : None
hypothesis          : None
sphinx              : None
blosc               : None
feather             : None
xlsxwriter          : None
lxml.etree          : None
html5lib            : None
pymysql             : None
psycopg2            : None
jinja2              : 3.1.4
IPython             : 8.30.0
pandas_datareader   : None
bs4                 : 4.12.3
bottleneck          : None
dataframe-api-compat: None
fastparquet         : None
fsspec              : 2024.12.0
gcsfs               : None
matplotlib          : 3.10.0
numba               : 0.60.0
numexpr             : None
odfpy               : None
openpyxl            : None
pandas_gbq          : None
pyarrow             : 18.1.0
pyreadstat          : None
pyxlsb              : None
s3fs                : None
scipy               : 1.14.1
sqlalchemy          : 2.0.36
tables              : None
tabulate            : 0.9.0
xarray              : None
xlrd                : 2.0.1
zstandard           : 0.23.0
tzdata              : 2024.2
qtpy                : None
pyqt5               : None

</details>
",,"{'url': 'https://api.github.com/repos/pandas-dev/pandas/issues/60596/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}",https://api.github.com/repos/pandas-dev/pandas/issues/60596/timeline,,
21,https://api.github.com/repos/pandas-dev/pandas/issues/60595,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas/issues/60595/labels{/name},https://api.github.com/repos/pandas-dev/pandas/issues/60595/comments,https://api.github.com/repos/pandas-dev/pandas/issues/60595/events,https://github.com/pandas-dev/pandas/pull/60595,2753398472,PR_kwDOAA0YD86F8xs-,60595,TST: Make test_sql.py parallelizable ,"{'login': 'UmbertoFasci', 'id': 48659857, 'node_id': 'MDQ6VXNlcjQ4NjU5ODU3', 'avatar_url': 'https://avatars.githubusercontent.com/u/48659857?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/UmbertoFasci', 'html_url': 'https://github.com/UmbertoFasci', 'followers_url': 'https://api.github.com/users/UmbertoFasci/followers', 'following_url': 'https://api.github.com/users/UmbertoFasci/following{/other_user}', 'gists_url': 'https://api.github.com/users/UmbertoFasci/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/UmbertoFasci/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/UmbertoFasci/subscriptions', 'organizations_url': 'https://api.github.com/users/UmbertoFasci/orgs', 'repos_url': 'https://api.github.com/users/UmbertoFasci/repos', 'events_url': 'https://api.github.com/users/UmbertoFasci/events{/privacy}', 'received_events_url': 'https://api.github.com/users/UmbertoFasci/received_events', 'type': 'User', 'user_view_type': 'public', 'site_admin': False}","[{'id': 127685, 'node_id': 'MDU6TGFiZWwxMjc2ODU=', 'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/Testing', 'name': 'Testing', 'color': 'C4A000', 'default': False, 'description': 'pandas testing functions or related to the test suite'}, {'id': 47232590, 'node_id': 'MDU6TGFiZWw0NzIzMjU5MA==', 'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/IO%20SQL', 'name': 'IO SQL', 'color': '5319e7', 'default': False, 'description': 'to_sql, read_sql, read_sql_query'}]",open,False,,[],,4,2024-12-20T19:51:17Z,2024-12-27T15:59:57Z,,CONTRIBUTOR,,False,"{'url': 'https://api.github.com/repos/pandas-dev/pandas/pulls/60595', 'html_url': 'https://github.com/pandas-dev/pandas/pull/60595', 'diff_url': 'https://github.com/pandas-dev/pandas/pull/60595.diff', 'patch_url': 'https://github.com/pandas-dev/pandas/pull/60595.patch', 'merged_at': None}","- [x] closes #60378 
- [x] All [code checks passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#pre-commit).

Description:

Generated individual uuids for individual hardcoded table name instances throughout the test cases as per the original feature description. Handling the test cases for connections with a shared database state as those which leverage the iris, or type table defined and created in fixtures requires more refactoring if needed to make parallelizable.

On that same note, the parallel safety of these particular connections should be further tested to see if they do require unique table names. 
",,"{'url': 'https://api.github.com/repos/pandas-dev/pandas/issues/60595/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}",https://api.github.com/repos/pandas-dev/pandas/issues/60595/timeline,,
22,https://api.github.com/repos/pandas-dev/pandas/issues/60594,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas/issues/60594/labels{/name},https://api.github.com/repos/pandas-dev/pandas/issues/60594/comments,https://api.github.com/repos/pandas-dev/pandas/issues/60594/events,https://github.com/pandas-dev/pandas/issues/60594,2753054681,I_kwDOAA0YD86kGEfZ,60594,BUG: Arrow Struct columns cannot be grouped on (ArrowNotImplementedError),"{'login': 'a-reich', 'id': 73507369, 'node_id': 'MDQ6VXNlcjczNTA3MzY5', 'avatar_url': 'https://avatars.githubusercontent.com/u/73507369?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/a-reich', 'html_url': 'https://github.com/a-reich', 'followers_url': 'https://api.github.com/users/a-reich/followers', 'following_url': 'https://api.github.com/users/a-reich/following{/other_user}', 'gists_url': 'https://api.github.com/users/a-reich/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/a-reich/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/a-reich/subscriptions', 'organizations_url': 'https://api.github.com/users/a-reich/orgs', 'repos_url': 'https://api.github.com/users/a-reich/repos', 'events_url': 'https://api.github.com/users/a-reich/events{/privacy}', 'received_events_url': 'https://api.github.com/users/a-reich/received_events', 'type': 'User', 'user_view_type': 'public', 'site_admin': False}","[{'id': 76811, 'node_id': 'MDU6TGFiZWw3NjgxMQ==', 'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/Bug', 'name': 'Bug', 'color': 'e10c02', 'default': False, 'description': None}, {'id': 233160, 'node_id': 'MDU6TGFiZWwyMzMxNjA=', 'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/Groupby', 'name': 'Groupby', 'color': '729FCF', 'default': False, 'description': None}, {'id': 42670965, 'node_id': 'MDU6TGFiZWw0MjY3MDk2NQ==', 'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/Error%20Reporting', 'name': 'Error Reporting', 'color': 'ffa0ff', 'default': False, 'description': 'Incorrect or improved errors from pandas'}, {'id': 3303158446, 'node_id': 'MDU6TGFiZWwzMzAzMTU4NDQ2', 'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/Arrow', 'name': 'Arrow', 'color': 'f9d0c4', 'default': False, 'description': 'pyarrow functionality'}]",open,False,,[],,1,2024-12-20T16:23:59Z,2024-12-20T21:19:48Z,,NONE,,,,"### Pandas version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pandas.pydata.org/docs/whatsnew/index.html) of pandas.

- [ ] I have confirmed this bug exists on the [main branch](https://pandas.pydata.org/docs/dev/getting_started/install.html#installing-the-development-version-of-pandas) of pandas.


### Reproducible Example

```python
import pandas as pd, pyarrow as pa
array = pa.StructArray.from_arrays([['a','b'], [1,2]], ('x','y'))
df = pd.DataFrame({'struct': pd.Series(array, dtype=pd.ArrowDtype(array.type)), 'val': range(2)})
df.groupby('struct').mean() # errors, traceback in description
```


### Issue Description

When a dataframe column contains an ArrowExtensionArray whose type is an Arrow struct, certain dataframe operations referencing the column error out, such as grouping by it. The above minimal example causes the following traceback for me:
```
---------------------------------------------------------------------------
ArrowNotImplementedError                  Traceback (most recent call last)
File ~/peopyl_density/.venv/lib/python3.12/site-packages/pandas/core/groupby/groupby.py:1942, in GroupBy._agg_py_fallback(self, how, values, ndim, alt)
   1941 try:
-> 1942     res_values = self._grouper.agg_series(ser, alt, preserve_dtype=True)
   1943 except Exception as err:

File ~/peopyl_density/.venv/lib/python3.12/site-packages/pandas/core/groupby/ops.py:864, in BaseGrouper.agg_series(self, obj, func, preserve_dtype)
    862     preserve_dtype = True
--> 864 result = self._aggregate_series_pure_python(obj, func)
    866 npvalues = lib.maybe_convert_objects(result, try_float=False)

File ~/peopyl_density/.venv/lib/python3.12/site-packages/pandas/core/groupby/ops.py:877, in BaseGrouper._aggregate_series_pure_python(self, obj, func)
    873 @final
    874 def _aggregate_series_pure_python(
    875     self, obj: Series, func: Callable
    876 ) -> npt.NDArray[np.object_]:
--> 877     _, _, ngroups = self.group_info
    879     result = np.empty(ngroups, dtype=""O"")

File properties.pyx:36, in pandas._libs.properties.CachedProperty.__get__()

File ~/peopyl_density/.venv/lib/python3.12/site-packages/pandas/core/groupby/ops.py:745, in BaseGrouper.group_info(self)
    743 @cache_readonly
    744 def group_info(self) -> tuple[npt.NDArray[np.intp], npt.NDArray[np.intp], int]:
--> 745     comp_ids, obs_group_ids = self._get_compressed_codes()
    747     ngroups = len(obs_group_ids)

File ~/peopyl_density/.venv/lib/python3.12/site-packages/pandas/core/groupby/ops.py:769, in BaseGrouper._get_compressed_codes(self)
    768 ping = self.groupings[0]
--> 769 return ping.codes, np.arange(len(ping._group_index), dtype=np.intp)

File ~/peopyl_density/.venv/lib/python3.12/site-packages/pandas/core/groupby/grouper.py:691, in Grouping.codes(self)
    689 @property
    690 def codes(self) -> npt.NDArray[np.signedinteger]:
--> 691     return self._codes_and_uniques[0]

File properties.pyx:36, in pandas._libs.properties.CachedProperty.__get__()

File ~/peopyl_density/.venv/lib/python3.12/site-packages/pandas/core/groupby/grouper.py:835, in Grouping._codes_and_uniques(self)
    831 else:
    832     # GH35667, replace dropna=False with use_na_sentinel=False
    833     # error: Incompatible types in assignment (expression has type ""Union[
    834     # ndarray[Any, Any], Index]"", variable has type ""Categorical"")
--> 835     codes, uniques = algorithms.factorize(  # type: ignore[assignment]
    836         self.grouping_vector, sort=self._sort, use_na_sentinel=self._dropna
    837     )
    838 return codes, uniques

File ~/peopyl_density/.venv/lib/python3.12/site-packages/pandas/core/algorithms.py:779, in factorize(values, sort, use_na_sentinel, size_hint)
    777 elif not isinstance(values, np.ndarray):
    778     # i.e. ExtensionArray
--> 779     codes, uniques = values.factorize(use_na_sentinel=use_na_sentinel)
    781 else:

File ~/peopyl_density/.venv/lib/python3.12/site-packages/pandas/core/arrays/arrow/array.py:1151, in ArrowExtensionArray.factorize(self, use_na_sentinel)
   1150 else:
-> 1151     encoded = data.dictionary_encode(null_encoding=null_encoding)
   1152 if encoded.length() == 0:

File ~/peopyl_density/.venv/lib/python3.12/site-packages/pyarrow/table.pxi:657, in pyarrow.lib.ChunkedArray.dictionary_encode()

File ~/peopyl_density/.venv/lib/python3.12/site-packages/pyarrow/_compute.pyx:598, in pyarrow._compute.call_function()

File ~/peopyl_density/.venv/lib/python3.12/site-packages/pyarrow/_compute.pyx:393, in pyarrow._compute.Function.call()

File ~/peopyl_density/.venv/lib/python3.12/site-packages/pyarrow/error.pxi:155, in pyarrow.lib.pyarrow_internal_check_status()

File ~/peopyl_density/.venv/lib/python3.12/site-packages/pyarrow/error.pxi:92, in pyarrow.lib.check_status()

ArrowNotImplementedError: Function 'dictionary_encode' has no kernel matching input types (struct<x: string, y: int64>)

The above exception was the direct cause of the following exception:

ArrowNotImplementedError                  Traceback (most recent call last)
Cell In[135], line 4
      2 array = pa.StructArray.from_arrays([['a','b'], [1,2]], ('x','y'))
      3 df = pd.DataFrame({'struct': pd.Series(array, dtype=pd.ArrowDtype(array.type)), 'val': range(2)})
----> 4 df.groupby('struct').mean()

File ~/peopyl_density/.venv/lib/python3.12/site-packages/pandas/core/groupby/groupby.py:2452, in GroupBy.mean(self, numeric_only, engine, engine_kwargs)
   2445     return self._numba_agg_general(
   2446         grouped_mean,
   2447         executor.float_dtype_mapping,
   2448         engine_kwargs,
   2449         min_periods=0,
   2450     )
   2451 else:
-> 2452     result = self._cython_agg_general(
   2453         ""mean"",
   2454         alt=lambda x: Series(x, copy=False).mean(numeric_only=numeric_only),
   2455         numeric_only=numeric_only,
   2456     )
   2457     return result.__finalize__(self.obj, method=""groupby"")

File ~/peopyl_density/.venv/lib/python3.12/site-packages/pandas/core/groupby/groupby.py:1998, in GroupBy._cython_agg_general(self, how, alt, numeric_only, min_count, **kwargs)
   1995     result = self._agg_py_fallback(how, values, ndim=data.ndim, alt=alt)
   1996     return result
-> 1998 new_mgr = data.grouped_reduce(array_func)
   1999 res = self._wrap_agged_manager(new_mgr)
   2000 if how in [""idxmin"", ""idxmax""]:

File ~/peopyl_density/.venv/lib/python3.12/site-packages/pandas/core/internals/managers.py:1472, in BlockManager.grouped_reduce(self, func)
   1470             result_blocks = extend_blocks(applied, result_blocks)
   1471     else:
-> 1472         applied = blk.apply(func)
   1473         result_blocks = extend_blocks(applied, result_blocks)
   1475 if len(result_blocks) == 0:

File ~/peopyl_density/.venv/lib/python3.12/site-packages/pandas/core/internals/blocks.py:393, in Block.apply(self, func, **kwargs)
    387 @final
    388 def apply(self, func, **kwargs) -> list[Block]:
    389     """"""
    390     apply the function to my values; return a block if we are not
    391     one
    392     """"""
--> 393     result = func(self.values, **kwargs)
    395     result = maybe_coerce_values(result)
    396     return self._split_op_result(result)

File ~/peopyl_density/.venv/lib/python3.12/site-packages/pandas/core/groupby/groupby.py:1995, in GroupBy._cython_agg_general.<locals>.array_func(values)
   1992     return result
   1994 assert alt is not None
-> 1995 result = self._agg_py_fallback(how, values, ndim=data.ndim, alt=alt)
   1996 return result

File ~/peopyl_density/.venv/lib/python3.12/site-packages/pandas/core/groupby/groupby.py:1946, in GroupBy._agg_py_fallback(self, how, values, ndim, alt)
   1944     msg = f""agg function failed [how->{how},dtype->{ser.dtype}]""
   1945     # preserve the kind of exception that raised
-> 1946     raise type(err)(msg) from err
   1948 if ser.dtype == object:
   1949     res_values = res_values.astype(object, copy=False)

ArrowNotImplementedError: agg function failed [how->mean,dtype->int64]
```

Feel free to let me know if this is more due to an issue with Arrow functionality that pandas relies on. If this can't/shouldn't be solved on the pandas side I can discuss on the Arrow issue tracker.

### Expected Behavior

I would generally expect grouping a dataframe on a column to succeed/work the same regardless of if the dtype is e.g. numpy based or a pyarrow primitive type rather than a struct.

### Installed Versions

<details>

INSTALLED VERSIONS
------------------
commit                : 0691c5cf90477d3503834d983f69350f250a6ff7
python                : 3.12.2
python-bits           : 64
OS                    : Linux
OS-release            : 5.15.167.4-microsoft-standard-WSL2
Version               : #1 SMP Tue Nov 5 00:21:55 UTC 2024
machine               : x86_64
processor             : x86_64
byteorder             : little
LC_ALL                : None
LANG                  : C.UTF-8
LOCALE                : C.UTF-8

pandas                : 2.2.3
numpy                 : 2.1.3
pytz                  : 2024.2
dateutil              : 2.9.0.post0
pip                   : None
Cython                : None
sphinx                : None
IPython               : 8.30.0
adbc-driver-postgresql: None
adbc-driver-sqlite    : None
bs4                   : 4.12.3
blosc                 : None
bottleneck            : None
dataframe-api-compat  : None
fastparquet           : None
fsspec                : None
html5lib              : None
hypothesis            : None
gcsfs                 : None
jinja2                : 3.1.4
lxml.etree            : None
matplotlib            : None
numba                 : None
numexpr               : None
odfpy                 : None
openpyxl              : None
pandas_gbq            : None
psycopg2              : None
pymysql               : None
pyarrow               : 18.1.0
pyreadstat            : None
pytest                : None
python-calamine       : None
pyxlsb                : None
s3fs                  : None
scipy                 : 1.14.1
sqlalchemy            : None
tables                : None
tabulate              : None
xarray                : None
xlrd                  : None
xlsxwriter            : None
zstandard             : None
tzdata                : 2024.2
qtpy                  : None
pyqt5                 : None
</details>
",,"{'url': 'https://api.github.com/repos/pandas-dev/pandas/issues/60594/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}",https://api.github.com/repos/pandas-dev/pandas/issues/60594/timeline,,
23,https://api.github.com/repos/pandas-dev/pandas/issues/60593,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas/issues/60593/labels{/name},https://api.github.com/repos/pandas-dev/pandas/issues/60593/comments,https://api.github.com/repos/pandas-dev/pandas/issues/60593/events,https://github.com/pandas-dev/pandas/issues/60593,2752910373,I_kwDOAA0YD86kFhQl,60593,API: `future.default_arg` for method-specific behavior changes,"{'login': 'rhshadrach', 'id': 45562402, 'node_id': 'MDQ6VXNlcjQ1NTYyNDAy', 'avatar_url': 'https://avatars.githubusercontent.com/u/45562402?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/rhshadrach', 'html_url': 'https://github.com/rhshadrach', 'followers_url': 'https://api.github.com/users/rhshadrach/followers', 'following_url': 'https://api.github.com/users/rhshadrach/following{/other_user}', 'gists_url': 'https://api.github.com/users/rhshadrach/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/rhshadrach/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/rhshadrach/subscriptions', 'organizations_url': 'https://api.github.com/users/rhshadrach/orgs', 'repos_url': 'https://api.github.com/users/rhshadrach/repos', 'events_url': 'https://api.github.com/users/rhshadrach/events{/privacy}', 'received_events_url': 'https://api.github.com/users/rhshadrach/received_events', 'type': 'User', 'user_view_type': 'public', 'site_admin': False}","[{'id': 35818298, 'node_id': 'MDU6TGFiZWwzNTgxODI5OA==', 'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/API%20Design', 'name': 'API Design', 'color': 'AD7FA8', 'default': False, 'description': None}, {'id': 87485152, 'node_id': 'MDU6TGFiZWw4NzQ4NTE1Mg==', 'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/Deprecate', 'name': 'Deprecate', 'color': '5319e7', 'default': False, 'description': 'Functionality to remove in pandas'}, {'id': 219960758, 'node_id': 'MDU6TGFiZWwyMTk5NjA3NTg=', 'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/Needs%20Discussion', 'name': 'Needs Discussion', 'color': '207de5', 'default': False, 'description': 'Requires discussion from core team before further action'}]",open,False,,[],,11,2024-12-20T15:00:52Z,2024-12-26T22:51:05Z,,MEMBER,,,,"Ref: https://github.com/pandas-dev/pandas/issues/60551#issuecomment-2556668313

Whenever possible, a deprecation should be performed without the introduction of a new argument for performing said deprecation. However there are times where we are changing the behavior of an existing function or method where the output will change on the same set of input arguments. For this, I think pandas should have a standard way of modifying the existing behavior.

I think there are two common cases when using pandas:
- The code I write is short-lived and when I get something working on one version of pandas, that's the only version it needs to work on.
- The code I write is maintained, and I will need to upgrade pandas and have it still perform correctly.

I think we can support both use cases by:
- Any time a particular method behavior changes, introduce a keyword-only argument `future=[True | False | no_default]` defaulting to `no_default`.
  - `future=True` gives the future behavior after the deprecation will be enforced.
  - `future=False` gives the current behavior, with no warning message.
  - `future=no_default` gives a warning message
- Introduce a global underride `future.default_arg = [True | False | no_default]` defaulting to `no_default`.

When e.g. `df.method(...)` is called without specifying the value of `future`, only then will the value `future.default_arg` will be used.

Users can keep the current behavior and globally disable all warnings by specifying `future.default_arg = False`. If they were to do so and upgrade across major versions of pandas, they will see breaking changes without ever getting any warnings. As such, I think the documentation on this should read something like:

>
>    future.default_arg : bool | no_default
>        Global underride of any pandas function that has a `future` argument. When the `future` argument is specified in the function call itself, this value will not be used. When `future.default_arg` is not specified (so has value `no_default`), calling  functions will warn on the upcoming change. When `future.default_arg` is set to `True`, the future behavior of functions will  be used. When `future.default_arg` is set to `False`, the current behavior of functions will be used without warning. In particular, if you specify `future.default_arg = False` and upgrade across major versions of pandas, you will experience breaking changes without warning! ",,"{'url': 'https://api.github.com/repos/pandas-dev/pandas/issues/60593/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}",https://api.github.com/repos/pandas-dev/pandas/issues/60593/timeline,,
24,https://api.github.com/repos/pandas-dev/pandas/issues/60591,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas/issues/60591/labels{/name},https://api.github.com/repos/pandas-dev/pandas/issues/60591/comments,https://api.github.com/repos/pandas-dev/pandas/issues/60591/events,https://github.com/pandas-dev/pandas/issues/60591,2752840163,I_kwDOAA0YD86kFQHj,60591,API: pass `ddof` down to Cythonised `std` / `var` in `groupby.agg`,"{'login': 'MarcoGorelli', 'id': 33491632, 'node_id': 'MDQ6VXNlcjMzNDkxNjMy', 'avatar_url': 'https://avatars.githubusercontent.com/u/33491632?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/MarcoGorelli', 'html_url': 'https://github.com/MarcoGorelli', 'followers_url': 'https://api.github.com/users/MarcoGorelli/followers', 'following_url': 'https://api.github.com/users/MarcoGorelli/following{/other_user}', 'gists_url': 'https://api.github.com/users/MarcoGorelli/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/MarcoGorelli/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/MarcoGorelli/subscriptions', 'organizations_url': 'https://api.github.com/users/MarcoGorelli/orgs', 'repos_url': 'https://api.github.com/users/MarcoGorelli/repos', 'events_url': 'https://api.github.com/users/MarcoGorelli/events{/privacy}', 'received_events_url': 'https://api.github.com/users/MarcoGorelli/received_events', 'type': 'User', 'user_view_type': 'public', 'site_admin': False}","[{'id': 233160, 'node_id': 'MDU6TGFiZWwyMzMxNjA=', 'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/Groupby', 'name': 'Groupby', 'color': '729FCF', 'default': False, 'description': None}, {'id': 35818298, 'node_id': 'MDU6TGFiZWwzNTgxODI5OA==', 'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/API%20Design', 'name': 'API Design', 'color': 'AD7FA8', 'default': False, 'description': None}]",open,False,,[],,1,2024-12-20T14:21:33Z,2024-12-20T14:38:19Z,,MEMBER,,,,"Say I want to do a `groupby` and perform various aggregations, e.g. I want to find `mean` and `std` of `b`. Easy:
```python
import pandas as pd

df = pd.DataFrame({'a': [1,1,2], 'b': [4,5,6]})
df.groupby('a').agg({'b': ['mean', 'std']})
```

What if I want to do the same with `ddof=0`? If was computing a single aggregation, I could do:
```python
print(df.groupby('a')['b'].std(ddof=0))
```
and that uses the Cythonized path.

However, I think the current pandas API doesn't allow a way of passing `ddof` to `'std'` when used in `.agg`. The workaround often suggested in StackOverflow is (😭 ):
```python
print(df.groupby('a').agg({'b': ['mean', lambda x: np.std(x)]}))
```
but that'll evade the Cythonized path, which is a missed opportunity",,"{'url': 'https://api.github.com/repos/pandas-dev/pandas/issues/60591/reactions', 'total_count': 1, '+1': 1, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}",https://api.github.com/repos/pandas-dev/pandas/issues/60591/timeline,,
25,https://api.github.com/repos/pandas-dev/pandas/issues/60589,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas/issues/60589/labels{/name},https://api.github.com/repos/pandas-dev/pandas/issues/60589/comments,https://api.github.com/repos/pandas-dev/pandas/issues/60589/events,https://github.com/pandas-dev/pandas/issues/60589,2749221119,I_kwDOAA0YD86j3cj_,60589,BUG: Test failures with 2.2.3 on Fedora Rawhide,"{'login': 'opoplawski', 'id': 814662, 'node_id': 'MDQ6VXNlcjgxNDY2Mg==', 'avatar_url': 'https://avatars.githubusercontent.com/u/814662?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/opoplawski', 'html_url': 'https://github.com/opoplawski', 'followers_url': 'https://api.github.com/users/opoplawski/followers', 'following_url': 'https://api.github.com/users/opoplawski/following{/other_user}', 'gists_url': 'https://api.github.com/users/opoplawski/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/opoplawski/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/opoplawski/subscriptions', 'organizations_url': 'https://api.github.com/users/opoplawski/orgs', 'repos_url': 'https://api.github.com/users/opoplawski/repos', 'events_url': 'https://api.github.com/users/opoplawski/events{/privacy}', 'received_events_url': 'https://api.github.com/users/opoplawski/received_events', 'type': 'User', 'user_view_type': 'public', 'site_admin': False}","[{'id': 76811, 'node_id': 'MDU6TGFiZWw3NjgxMQ==', 'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/Bug', 'name': 'Bug', 'color': 'e10c02', 'default': False, 'description': None}, {'id': 307649777, 'node_id': 'MDU6TGFiZWwzMDc2NDk3Nzc=', 'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/Needs%20Info', 'name': 'Needs Info', 'color': '207de5', 'default': False, 'description': 'Clarification about behavior needed to assess issue'}]",open,False,,[],,5,2024-12-19T04:30:31Z,2024-12-24T09:47:49Z,,NONE,,,,"### Pandas version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pandas.pydata.org/docs/whatsnew/index.html) of pandas.

- [ ] I have confirmed this bug exists on the [main branch](https://pandas.pydata.org/docs/dev/getting_started/install.html#installing-the-development-version-of-pandas) of pandas.


### Reproducible Example

```python
============================= test session starts ==============================
platform linux -- Python 3.13.1, pytest-8.3.4, pluggy-1.5.0 -- /usr/bin/python3
cachedir: /builddir/build/BUILD/python-pandas-2.2.3-build/pandas-2.2.3/_empty/pytest-cache
hypothesis profile 'ci' -> deadline=None, suppress_health_check=[HealthCheck.too_slow, HealthCheck.differing_executors], database=DirectoryBasedExampleDatabase(PosixPath('/builddir/build/BUILD/python-pandas-2.2.3-build/pandas-2.2.3/_empty/.hypothesis/examples'))
rootdir: /builddir/build/BUILD/python-pandas-2.2.3-build/BUILDROOT/usr/lib64/python3.13/site-packages/pandas
configfile: pyproject.toml
plugins: asyncio-0.24.0, xdist-3.6.1, hypothesis-6.104.2
asyncio: mode=Mode.STRICT, default_loop_scope=None
created: 1/1 worker
```
```
=================================== FAILURES ===================================
____________________ test_array_inference[data7-expected7] _____________________
[gw0] linux -- Python 3.13.1 /usr/bin/python3
data = [datetime.datetime(2000, 1, 1, 0, 0, tzinfo=<DstTzInfo 'CET' LMT+0:18:00 STD>), datetime.datetime(2001, 1, 1, 0, 0, tzinfo=<DstTzInfo 'CET' LMT+0:18:00 STD>)]
expected = <DatetimeArray>
['2000-01-01 00:00:00+01:00', '2001-01-01 00:00:00+01:00']
Length: 2, dtype: datetime64[ns, CET]
    @pytest.mark.parametrize(
        ""data, expected"",
        [
            # period
            (
                [pd.Period(""2000"", ""D""), pd.Period(""2001"", ""D"")],
                period_array([""2000"", ""2001""], freq=""D""),
            ),
            # interval
            ([pd.Interval(0, 1), pd.Interval(1, 2)], IntervalArray.from_breaks([0, 1, 2])),
            # datetime
            (
                [pd.Timestamp(""2000""), pd.Timestamp(""2001"")],
                DatetimeArray._from_sequence([""2000"", ""2001""], dtype=""M8[ns]""),
            ),
            (
                [datetime.datetime(2000, 1, 1), datetime.datetime(2001, 1, 1)],
                DatetimeArray._from_sequence([""2000"", ""2001""], dtype=""M8[ns]""),
            ),
            (
                np.array([1, 2], dtype=""M8[ns]""),
                DatetimeArray._from_sequence(np.array([1, 2], dtype=""M8[ns]"")),
            ),
            (
                np.array([1, 2], dtype=""M8[us]""),
                DatetimeArray._simple_new(
                    np.array([1, 2], dtype=""M8[us]""), dtype=np.dtype(""M8[us]"")
                ),
            ),
            # datetimetz
            (
                [pd.Timestamp(""2000"", tz=""CET""), pd.Timestamp(""2001"", tz=""CET"")],
                DatetimeArray._from_sequence(
                    [""2000"", ""2001""], dtype=pd.DatetimeTZDtype(tz=""CET"", unit=""ns"")
                ),
            ),
            (
                [
                    datetime.datetime(2000, 1, 1, tzinfo=cet),
                    datetime.datetime(2001, 1, 1, tzinfo=cet),
                ],
                DatetimeArray._from_sequence(
                    [""2000"", ""2001""], dtype=pd.DatetimeTZDtype(tz=cet, unit=""ns"")
                ),
            ),
            # timedelta
            (
                [pd.Timedelta(""1h""), pd.Timedelta(""2h"")],
                TimedeltaArray._from_sequence([""1h"", ""2h""], dtype=""m8[ns]""),
            ),
            (
                np.array([1, 2], dtype=""m8[ns]""),
                TimedeltaArray._from_sequence(np.array([1, 2], dtype=""m8[ns]"")),
            ),
            (
                np.array([1, 2], dtype=""m8[us]""),
                TimedeltaArray._from_sequence(np.array([1, 2], dtype=""m8[us]"")),
            ),
            # integer
            ([1, 2], IntegerArray._from_sequence([1, 2], dtype=""Int64"")),
            ([1, None], IntegerArray._from_sequence([1, None], dtype=""Int64"")),
            ([1, pd.NA], IntegerArray._from_sequence([1, pd.NA], dtype=""Int64"")),
            ([1, np.nan], IntegerArray._from_sequence([1, np.nan], dtype=""Int64"")),
            # float
            ([0.1, 0.2], FloatingArray._from_sequence([0.1, 0.2], dtype=""Float64"")),
            ([0.1, None], FloatingArray._from_sequence([0.1, pd.NA], dtype=""Float64"")),
            ([0.1, np.nan], FloatingArray._from_sequence([0.1, pd.NA], dtype=""Float64"")),
            ([0.1, pd.NA], FloatingArray._from_sequence([0.1, pd.NA], dtype=""Float64"")),
            # integer-like float
            ([1.0, 2.0], FloatingArray._from_sequence([1.0, 2.0], dtype=""Float64"")),
            ([1.0, None], FloatingArray._from_sequence([1.0, pd.NA], dtype=""Float64"")),
            ([1.0, np.nan], FloatingArray._from_sequence([1.0, pd.NA], dtype=""Float64"")),
            ([1.0, pd.NA], FloatingArray._from_sequence([1.0, pd.NA], dtype=""Float64"")),
            # mixed-integer-float
            ([1, 2.0], FloatingArray._from_sequence([1.0, 2.0], dtype=""Float64"")),
            (
                [1, np.nan, 2.0],
                FloatingArray._from_sequence([1.0, None, 2.0], dtype=""Float64""),
            ),
            # string
            (
                [""a"", ""b""],
                pd.StringDtype()
                .construct_array_type()
                ._from_sequence([""a"", ""b""], dtype=pd.StringDtype()),
            ),
            (
                [""a"", None],
                pd.StringDtype()
                .construct_array_type()
                ._from_sequence([""a"", None], dtype=pd.StringDtype()),
            ),
            # Boolean
            ([True, False], BooleanArray._from_sequence([True, False], dtype=""boolean"")),
            ([True, None], BooleanArray._from_sequence([True, None], dtype=""boolean"")),
        ],
    )
    def test_array_inference(data, expected):
        result = pd.array(data)
>       tm.assert_equal(result, expected)
../../BUILDROOT/usr/lib64/python3.13/site-packages/pandas/tests/arrays/test_array.py:377: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
left = array(['1999-12-31T23:42:00.000000000', '2000-12-31T23:42:00.000000000'],
      dtype='datetime64[ns]')
right = array(['1999-12-31T23:00:00.000000000', '2000-12-31T23:00:00.000000000'],
      dtype='datetime64[ns]')
err_msg = None
    def _raise(left, right, err_msg) -> NoReturn:
        if err_msg is None:
            if left.shape != right.shape:
                raise_assert_detail(
                    obj, f""{obj} shapes are different"", left.shape, right.shape
                )
    
            diff = 0
            for left_arr, right_arr in zip(left, right):
                # count up differences
                if not array_equivalent(left_arr, right_arr, strict_nan=strict_nan):
                    diff += 1
    
            diff = diff * 100.0 / left.size
            msg = f""{obj} values are different ({np.round(diff, 5)} %)""
>           raise_assert_detail(obj, msg, left, right, index_values=index_values)
E           AssertionError: DatetimeArray._ndarray are different
E           
E           DatetimeArray._ndarray values are different (100.0 %)
E           [left]:  [1999-12-31T23:42:00.000000000, 2000-12-31T23:42:00.000000000]
E           [right]: [1999-12-31T23:00:00.000000000, 2000-12-31T23:00:00.000000000]
../../BUILDROOT/usr/lib64/python3.13/site-packages/pandas/_testing/asserters.py:684: AssertionError
```

Full build log with more test failures is here: https://kojipkgs.fedoraproject.org//work/tasks/9043/126999043/build.log
```


### Issue Description

We are updating Fedora to pandas 2.2.3 and numpy 2.0.5 but are getting test failures.

### Expected Behavior

No test failures

### Installed Versions

<details>

2.2.3

</details>
",,"{'url': 'https://api.github.com/repos/pandas-dev/pandas/issues/60589/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}",https://api.github.com/repos/pandas-dev/pandas/issues/60589/timeline,,
26,https://api.github.com/repos/pandas-dev/pandas/issues/60585,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas/issues/60585/labels{/name},https://api.github.com/repos/pandas-dev/pandas/issues/60585/comments,https://api.github.com/repos/pandas-dev/pandas/issues/60585/events,https://github.com/pandas-dev/pandas/issues/60585,2744296164,I_kwDOAA0YD86jkqLk,60585,ENH: Add the `observed` parameter to `get_dummies`,"{'login': 'alonme', 'id': 25847554, 'node_id': 'MDQ6VXNlcjI1ODQ3NTU0', 'avatar_url': 'https://avatars.githubusercontent.com/u/25847554?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/alonme', 'html_url': 'https://github.com/alonme', 'followers_url': 'https://api.github.com/users/alonme/followers', 'following_url': 'https://api.github.com/users/alonme/following{/other_user}', 'gists_url': 'https://api.github.com/users/alonme/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/alonme/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/alonme/subscriptions', 'organizations_url': 'https://api.github.com/users/alonme/orgs', 'repos_url': 'https://api.github.com/users/alonme/repos', 'events_url': 'https://api.github.com/users/alonme/events{/privacy}', 'received_events_url': 'https://api.github.com/users/alonme/received_events', 'type': 'User', 'user_view_type': 'public', 'site_admin': False}","[{'id': 76812, 'node_id': 'MDU6TGFiZWw3NjgxMg==', 'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/Enhancement', 'name': 'Enhancement', 'color': '4E9A06', 'default': False, 'description': None}, {'id': 78527356, 'node_id': 'MDU6TGFiZWw3ODUyNzM1Ng==', 'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/Categorical', 'name': 'Categorical', 'color': 'e11d21', 'default': False, 'description': 'Categorical Data Type'}, {'id': 1954720290, 'node_id': 'MDU6TGFiZWwxOTU0NzIwMjkw', 'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/Needs%20Triage', 'name': 'Needs Triage', 'color': '0052cc', 'default': False, 'description': 'Issue that has not been reviewed by a pandas team member'}]",open,False,,[],,0,2024-12-17T08:49:33Z,2024-12-17T15:28:43Z,,CONTRIBUTOR,,,,"### Feature Type

- [X] Adding new functionality to pandas

- [ ] Changing existing functionality in pandas

- [ ] Removing existing functionality in pandas


### Problem Description

The `get_dummies` function creates columns for all possible values of categorical series and not the ones that are observed, or are actually in the passed dataframe

Example:

```python
In [1]: import pandas as pd

In [2]: df = pd.DataFrame({'letter':['a','b','c']})

In [3]: pd.get_dummies(df[df['letter'] == 'a'])
Out[3]:
   letter_a
0         1

In [4]: df['letter'] = df['letter'].astype(""category"")

In [5]: pd.get_dummies(df[df['letter'] == 'a'])
Out[5]:
   letter_a  letter_b  letter_c
0         1         0         0
```

### Feature Description

Add the `observed` parameter to the `get_dummies` function, which will have the same behavior as the parameter with the same name in the [groupby functions](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.groupby.html) 

### Alternative Solutions

1. Change the behavior to always use the observed values only
2. Document this behavior so its clear to users (users can remove the unneeded columns later if they want to)

### Additional Context

_No response_",,"{'url': 'https://api.github.com/repos/pandas-dev/pandas/issues/60585/reactions', 'total_count': 2, '+1': 2, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}",https://api.github.com/repos/pandas-dev/pandas/issues/60585/timeline,,
27,https://api.github.com/repos/pandas-dev/pandas/issues/60583,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas/issues/60583/labels{/name},https://api.github.com/repos/pandas-dev/pandas/issues/60583/comments,https://api.github.com/repos/pandas-dev/pandas/issues/60583/events,https://github.com/pandas-dev/pandas/issues/60583,2743573661,I_kwDOAA0YD86jh5yd,60583,BUG: `Timestamp.normalize()` can overflow silently,"{'login': 'wjandrea', 'id': 22385371, 'node_id': 'MDQ6VXNlcjIyMzg1Mzcx', 'avatar_url': 'https://avatars.githubusercontent.com/u/22385371?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/wjandrea', 'html_url': 'https://github.com/wjandrea', 'followers_url': 'https://api.github.com/users/wjandrea/followers', 'following_url': 'https://api.github.com/users/wjandrea/following{/other_user}', 'gists_url': 'https://api.github.com/users/wjandrea/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/wjandrea/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/wjandrea/subscriptions', 'organizations_url': 'https://api.github.com/users/wjandrea/orgs', 'repos_url': 'https://api.github.com/users/wjandrea/repos', 'events_url': 'https://api.github.com/users/wjandrea/events{/privacy}', 'received_events_url': 'https://api.github.com/users/wjandrea/received_events', 'type': 'User', 'user_view_type': 'public', 'site_admin': False}","[{'id': 76811, 'node_id': 'MDU6TGFiZWw3NjgxMQ==', 'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/Bug', 'name': 'Bug', 'color': 'e10c02', 'default': False, 'description': None}, {'id': 3877216987, 'node_id': 'LA_kwDOAA0YD87nGaLb', 'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/Timestamp', 'name': 'Timestamp', 'color': '5DE3E8', 'default': False, 'description': 'pd.Timestamp and associated methods'}]",open,False,,[],,5,2024-12-16T23:06:17Z,2024-12-31T09:54:26Z,,CONTRIBUTOR,,,,"### Pandas version checks

- [X] I have checked that this issue has not already been reported.
    - Query: `is:issue normalize overflow`
- [X] I have confirmed this bug exists on the [latest version](https://pandas.pydata.org/docs/whatsnew/index.html) of pandas.
- [X] I have confirmed this bug exists on the [main branch](https://pandas.pydata.org/docs/dev/getting_started/install.html#installing-the-development-version-of-pandas) of pandas.

### Issue description

I was trying to get the minimum date, so I tried `pd.Timestamp.min.normalize()` before realizing that would be out of range, but what's weird is that it overflows without warning:

```py
>>> pd.Timestamp.min
Timestamp('1677-09-21 00:12:43.145224193')
>>> pd.Timestamp.min.normalize()
Timestamp('2262-04-11 23:34:33.709551616')
```

For reference:
```py
>>> pd.Timestamp.max
Timestamp('2262-04-11 23:47:16.854775807')
```

Compare that to `.floor('D')`, which I thought would be equivalent, but it raises:

```py
>>> pd.Timestamp.min.floor('D')
OverflowError: value too large


The above exception was the direct cause of the following exception:

OutOfBoundsDatetime: Cannot round 1677-09-21 00:12:43.145224193 to freq=<Day> without overflow
```

as well as `.round('D')` (same error).

Sidenote: What I really wanted was `.ceil('D')`, which gets the first whole day:

```py
>>> pd.Timestamp.min.ceil('D')
Timestamp('1677-09-22 00:00:00')
```

### Installed Versions

<details>

```none
INSTALLED VERSIONS
------------------
commit                : d41884b2dd0823dc6288ab65d06650302e903c6b
python                : 3.12.8
python-bits           : 64
OS                    : Linux
OS-release            : 5.4.0-202-generic
Version               : #222-Ubuntu SMP Fri Nov 8 14:45:04 UTC 2024
machine               : x86_64
processor             : x86_64
byteorder             : little
LC_ALL                : None
LANG                  : fr_CA.UTF-8
LOCALE                : fr_CA.UTF-8

pandas                : 3.0.0.dev0+1777.gd41884b2dd
numpy                 : 2.1.0.dev0+git20240403.e59c074
dateutil              : 2.9.0.post0
pip                   : 24.3.1
Cython                : None
sphinx                : None
IPython               : 8.22.2
adbc-driver-postgresql: None
adbc-driver-sqlite    : None
bs4                   : None
blosc                 : None
bottleneck            : None
fastparquet           : None
fsspec                : None
html5lib              : None
hypothesis            : None
gcsfs                 : None
jinja2                : None
lxml.etree            : None
matplotlib            : None
numba                 : None
numexpr               : None
odfpy                 : None
openpyxl              : None
psycopg2              : None
pymysql               : None
pyarrow               : None
pyreadstat            : None
pytest                : None
python-calamine       : None
pytz                  : 2024.1
pyxlsb                : None
s3fs                  : None
scipy                 : None
sqlalchemy            : None
tables                : None
tabulate              : None
xarray                : None
xlrd                  : None
xlsxwriter            : None
zstandard             : None
tzdata                : 2024.1
qtpy                  : None
pyqt5                 : None
```

</details>
",,"{'url': 'https://api.github.com/repos/pandas-dev/pandas/issues/60583/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}",https://api.github.com/repos/pandas-dev/pandas/issues/60583/timeline,,
28,https://api.github.com/repos/pandas-dev/pandas/issues/60579,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas/issues/60579/labels{/name},https://api.github.com/repos/pandas-dev/pandas/issues/60579/comments,https://api.github.com/repos/pandas-dev/pandas/issues/60579/events,https://github.com/pandas-dev/pandas/pull/60579,2741334856,PR_kwDOAA0YD86FTMe-,60579,ENH: Add first and last aggregations to Rolling and Expanding,"{'login': 'snitish', 'id': 7503884, 'node_id': 'MDQ6VXNlcjc1MDM4ODQ=', 'avatar_url': 'https://avatars.githubusercontent.com/u/7503884?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/snitish', 'html_url': 'https://github.com/snitish', 'followers_url': 'https://api.github.com/users/snitish/followers', 'following_url': 'https://api.github.com/users/snitish/following{/other_user}', 'gists_url': 'https://api.github.com/users/snitish/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/snitish/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/snitish/subscriptions', 'organizations_url': 'https://api.github.com/users/snitish/orgs', 'repos_url': 'https://api.github.com/users/snitish/repos', 'events_url': 'https://api.github.com/users/snitish/events{/privacy}', 'received_events_url': 'https://api.github.com/users/snitish/received_events', 'type': 'User', 'user_view_type': 'public', 'site_admin': False}","[{'id': 76812, 'node_id': 'MDU6TGFiZWw3NjgxMg==', 'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/Enhancement', 'name': 'Enhancement', 'color': '4E9A06', 'default': False, 'description': None}, {'id': 1045950827, 'node_id': 'MDU6TGFiZWwxMDQ1OTUwODI3', 'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/Window', 'name': 'Window', 'color': 'd4c5f9', 'default': False, 'description': 'rolling, ewma, expanding'}]",open,False,,[],,1,2024-12-16T04:57:58Z,2024-12-16T20:11:44Z,,CONTRIBUTOR,,False,"{'url': 'https://api.github.com/repos/pandas-dev/pandas/pulls/60579', 'html_url': 'https://github.com/pandas-dev/pandas/pull/60579', 'diff_url': 'https://github.com/pandas-dev/pandas/pull/60579.diff', 'patch_url': 'https://github.com/pandas-dev/pandas/pull/60579.patch', 'merged_at': None}","- [ ] closes #33155 (Replace xxxx with the GitHub issue number)
- [ ] [Tests added and passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#writing-tests) if fixing a bug or adding a new feature
- [ ] All [code checks passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#pre-commit).
- [ ] Added [type annotations](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#type-hints) to new arguments/methods/functions.
- [ ] Added an entry in the latest `doc/source/whatsnew/v3.0.0.rst` file if fixing a bug or adding a new feature.
",,"{'url': 'https://api.github.com/repos/pandas-dev/pandas/issues/60579/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}",https://api.github.com/repos/pandas-dev/pandas/issues/60579/timeline,,
29,https://api.github.com/repos/pandas-dev/pandas/issues/60576,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas/issues/60576/labels{/name},https://api.github.com/repos/pandas-dev/pandas/issues/60576/comments,https://api.github.com/repos/pandas-dev/pandas/issues/60576/events,https://github.com/pandas-dev/pandas/issues/60576,2740661747,I_kwDOAA0YD86jWy3z,60576,DOC: fix docstring validation errors for pandas.core and pandas.errors,"{'login': 'sunlight798', 'id': 138234530, 'node_id': 'U_kgDOCD1Kog', 'avatar_url': 'https://avatars.githubusercontent.com/u/138234530?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/sunlight798', 'html_url': 'https://github.com/sunlight798', 'followers_url': 'https://api.github.com/users/sunlight798/followers', 'following_url': 'https://api.github.com/users/sunlight798/following{/other_user}', 'gists_url': 'https://api.github.com/users/sunlight798/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/sunlight798/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/sunlight798/subscriptions', 'organizations_url': 'https://api.github.com/users/sunlight798/orgs', 'repos_url': 'https://api.github.com/users/sunlight798/repos', 'events_url': 'https://api.github.com/users/sunlight798/events{/privacy}', 'received_events_url': 'https://api.github.com/users/sunlight798/received_events', 'type': 'User', 'user_view_type': 'public', 'site_admin': False}","[{'id': 2365504893, 'node_id': 'MDU6TGFiZWwyMzY1NTA0ODkz', 'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/Closing%20Candidate', 'name': 'Closing Candidate', 'color': 'be21f2', 'default': False, 'description': 'May be closeable, needs more eyeballs'}]",open,False,,[],,1,2024-12-15T14:08:53Z,2024-12-15T21:24:10Z,,CONTRIBUTOR,,,,"> follow up on issues  #59698, #59458 and #58063 pandas has a script for validating docstrings:
> 
> https://github.com/pandas-dev/pandas/blob/b0192c70610a9db593968374ea60d189daaaccc7/ci/code_checks.sh#L86-L100
> 
> Currently, some methods fail docstring validation check. The task here is:
> 
> * take 2-4 methods
> * run: `scripts/validate_docstrings.py <method-name>`
> * run `pytest pandas/tests/scalar/test_nat.py::test_nat_doc_strings`
> * fix the docstrings according to whatever error is reported
> * remove those methods from `code_checks.sh` script
> * commit, push, open pull request
> 
> Example:
> 
> ```
>  scripts/validate_docstrings.py pandas.Timedelta.ceil
> ```
> 
> pandas.Timedelta.ceil fails with the SA01 and ES01 errors
> 
> ```
> ################################################################################
> ################################## Validation ##################################
> ################################################################################
> 
> 2 Errors found for `pandas.Timedelta.ceil`:
>         ES01    No extended summary found
>         SA01    See Also section not found
> ```
> 
> Please don't comment `take` as multiple people can work on this issue. You also don't need to ask for permission to work on this, just comment on which methods are you going to work.
> 
> If you're new contributor, please check the [contributing guide](https://pandas.pydata.org/docs/dev/development/contributing.html)
> 
> thanks @natmokval for giving me the idea for this issue.",,"{'url': 'https://api.github.com/repos/pandas-dev/pandas/issues/60576/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}",https://api.github.com/repos/pandas-dev/pandas/issues/60576/timeline,,
